// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow_serving/core/logging.proto

package tensorflow.serving;

public final class Logging {
  private Logging() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.LogMetadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     * @return Whether the modelSpec field is set.
     */
    boolean hasModelSpec();
    /**
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     * @return The modelSpec.
     */
    tensorflow.serving.Model.ModelSpec getModelSpec();
    /**
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    tensorflow.serving.Model.ModelSpecOrBuilder getModelSpecOrBuilder();

    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     * @return Whether the samplingConfig field is set.
     */
    boolean hasSamplingConfig();
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     * @return The samplingConfig.
     */
    tensorflow.serving.LoggingConfigOuterClass.SamplingConfig getSamplingConfig();
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     */
    tensorflow.serving.LoggingConfigOuterClass.SamplingConfigOrBuilder getSamplingConfigOrBuilder();

    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @return A list containing the savedModelTags.
     */
    java.util.List<java.lang.String>
        getSavedModelTagsList();
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @return The count of savedModelTags.
     */
    int getSavedModelTagsCount();
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @param index The index of the element to return.
     * @return The savedModelTags at the given index.
     */
    java.lang.String getSavedModelTags(int index);
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the savedModelTags at the given index.
     */
    com.google.protobuf.ByteString
        getSavedModelTagsBytes(int index);
  }
  /**
   * <pre>
   * Metadata logged along with the request logs.
   * </pre>
   *
   * Protobuf type {@code tensorflow.serving.LogMetadata}
   */
  public  static final class LogMetadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.LogMetadata)
      LogMetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogMetadata.newBuilder() to construct.
    private LogMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogMetadata() {
      savedModelTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LogMetadata();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tensorflow.serving.Model.ModelSpec.Builder subBuilder = null;
              if (modelSpec_ != null) {
                subBuilder = modelSpec_.toBuilder();
              }
              modelSpec_ = input.readMessage(tensorflow.serving.Model.ModelSpec.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(modelSpec_);
                modelSpec_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.Builder subBuilder = null;
              if (samplingConfig_ != null) {
                subBuilder = samplingConfig_.toBuilder();
              }
              samplingConfig_ = input.readMessage(tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(samplingConfig_);
                samplingConfig_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                savedModelTags_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              savedModelTags_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          savedModelTags_ = savedModelTags_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tensorflow.serving.Logging.internal_static_tensorflow_serving_LogMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tensorflow.serving.Logging.internal_static_tensorflow_serving_LogMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tensorflow.serving.Logging.LogMetadata.class, tensorflow.serving.Logging.LogMetadata.Builder.class);
    }

    public static final int MODEL_SPEC_FIELD_NUMBER = 1;
    private tensorflow.serving.Model.ModelSpec modelSpec_;
    /**
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     * @return Whether the modelSpec field is set.
     */
    public boolean hasModelSpec() {
      return modelSpec_ != null;
    }
    /**
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     * @return The modelSpec.
     */
    public tensorflow.serving.Model.ModelSpec getModelSpec() {
      return modelSpec_ == null ? tensorflow.serving.Model.ModelSpec.getDefaultInstance() : modelSpec_;
    }
    /**
     * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
     */
    public tensorflow.serving.Model.ModelSpecOrBuilder getModelSpecOrBuilder() {
      return getModelSpec();
    }

    public static final int SAMPLING_CONFIG_FIELD_NUMBER = 2;
    private tensorflow.serving.LoggingConfigOuterClass.SamplingConfig samplingConfig_;
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     * @return Whether the samplingConfig field is set.
     */
    public boolean hasSamplingConfig() {
      return samplingConfig_ != null;
    }
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     * @return The samplingConfig.
     */
    public tensorflow.serving.LoggingConfigOuterClass.SamplingConfig getSamplingConfig() {
      return samplingConfig_ == null ? tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.getDefaultInstance() : samplingConfig_;
    }
    /**
     * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
     */
    public tensorflow.serving.LoggingConfigOuterClass.SamplingConfigOrBuilder getSamplingConfigOrBuilder() {
      return getSamplingConfig();
    }

    public static final int SAVED_MODEL_TAGS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList savedModelTags_;
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @return A list containing the savedModelTags.
     */
    public com.google.protobuf.ProtocolStringList
        getSavedModelTagsList() {
      return savedModelTags_;
    }
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @return The count of savedModelTags.
     */
    public int getSavedModelTagsCount() {
      return savedModelTags_.size();
    }
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @param index The index of the element to return.
     * @return The savedModelTags at the given index.
     */
    public java.lang.String getSavedModelTags(int index) {
      return savedModelTags_.get(index);
    }
    /**
     * <pre>
     * List of tags used to load the relevant MetaGraphDef from SavedModel.
     * </pre>
     *
     * <code>repeated string saved_model_tags = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the savedModelTags at the given index.
     */
    public com.google.protobuf.ByteString
        getSavedModelTagsBytes(int index) {
      return savedModelTags_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (modelSpec_ != null) {
        output.writeMessage(1, getModelSpec());
      }
      if (samplingConfig_ != null) {
        output.writeMessage(2, getSamplingConfig());
      }
      for (int i = 0; i < savedModelTags_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, savedModelTags_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (modelSpec_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getModelSpec());
      }
      if (samplingConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSamplingConfig());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < savedModelTags_.size(); i++) {
          dataSize += computeStringSizeNoTag(savedModelTags_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSavedModelTagsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tensorflow.serving.Logging.LogMetadata)) {
        return super.equals(obj);
      }
      tensorflow.serving.Logging.LogMetadata other = (tensorflow.serving.Logging.LogMetadata) obj;

      if (hasModelSpec() != other.hasModelSpec()) return false;
      if (hasModelSpec()) {
        if (!getModelSpec()
            .equals(other.getModelSpec())) return false;
      }
      if (hasSamplingConfig() != other.hasSamplingConfig()) return false;
      if (hasSamplingConfig()) {
        if (!getSamplingConfig()
            .equals(other.getSamplingConfig())) return false;
      }
      if (!getSavedModelTagsList()
          .equals(other.getSavedModelTagsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasModelSpec()) {
        hash = (37 * hash) + MODEL_SPEC_FIELD_NUMBER;
        hash = (53 * hash) + getModelSpec().hashCode();
      }
      if (hasSamplingConfig()) {
        hash = (37 * hash) + SAMPLING_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getSamplingConfig().hashCode();
      }
      if (getSavedModelTagsCount() > 0) {
        hash = (37 * hash) + SAVED_MODEL_TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getSavedModelTagsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tensorflow.serving.Logging.LogMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tensorflow.serving.Logging.LogMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.serving.Logging.LogMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tensorflow.serving.Logging.LogMetadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Metadata logged along with the request logs.
     * </pre>
     *
     * Protobuf type {@code tensorflow.serving.LogMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.LogMetadata)
        tensorflow.serving.Logging.LogMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tensorflow.serving.Logging.internal_static_tensorflow_serving_LogMetadata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tensorflow.serving.Logging.internal_static_tensorflow_serving_LogMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tensorflow.serving.Logging.LogMetadata.class, tensorflow.serving.Logging.LogMetadata.Builder.class);
      }

      // Construct using tensorflow.serving.Logging.LogMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (modelSpecBuilder_ == null) {
          modelSpec_ = null;
        } else {
          modelSpec_ = null;
          modelSpecBuilder_ = null;
        }
        if (samplingConfigBuilder_ == null) {
          samplingConfig_ = null;
        } else {
          samplingConfig_ = null;
          samplingConfigBuilder_ = null;
        }
        savedModelTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tensorflow.serving.Logging.internal_static_tensorflow_serving_LogMetadata_descriptor;
      }

      @java.lang.Override
      public tensorflow.serving.Logging.LogMetadata getDefaultInstanceForType() {
        return tensorflow.serving.Logging.LogMetadata.getDefaultInstance();
      }

      @java.lang.Override
      public tensorflow.serving.Logging.LogMetadata build() {
        tensorflow.serving.Logging.LogMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tensorflow.serving.Logging.LogMetadata buildPartial() {
        tensorflow.serving.Logging.LogMetadata result = new tensorflow.serving.Logging.LogMetadata(this);
        int from_bitField0_ = bitField0_;
        if (modelSpecBuilder_ == null) {
          result.modelSpec_ = modelSpec_;
        } else {
          result.modelSpec_ = modelSpecBuilder_.build();
        }
        if (samplingConfigBuilder_ == null) {
          result.samplingConfig_ = samplingConfig_;
        } else {
          result.samplingConfig_ = samplingConfigBuilder_.build();
        }
        if (((bitField0_ & 0x00000001) != 0)) {
          savedModelTags_ = savedModelTags_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.savedModelTags_ = savedModelTags_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tensorflow.serving.Logging.LogMetadata) {
          return mergeFrom((tensorflow.serving.Logging.LogMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tensorflow.serving.Logging.LogMetadata other) {
        if (other == tensorflow.serving.Logging.LogMetadata.getDefaultInstance()) return this;
        if (other.hasModelSpec()) {
          mergeModelSpec(other.getModelSpec());
        }
        if (other.hasSamplingConfig()) {
          mergeSamplingConfig(other.getSamplingConfig());
        }
        if (!other.savedModelTags_.isEmpty()) {
          if (savedModelTags_.isEmpty()) {
            savedModelTags_ = other.savedModelTags_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSavedModelTagsIsMutable();
            savedModelTags_.addAll(other.savedModelTags_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tensorflow.serving.Logging.LogMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tensorflow.serving.Logging.LogMetadata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private tensorflow.serving.Model.ModelSpec modelSpec_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tensorflow.serving.Model.ModelSpec, tensorflow.serving.Model.ModelSpec.Builder, tensorflow.serving.Model.ModelSpecOrBuilder> modelSpecBuilder_;
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       * @return Whether the modelSpec field is set.
       */
      public boolean hasModelSpec() {
        return modelSpecBuilder_ != null || modelSpec_ != null;
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       * @return The modelSpec.
       */
      public tensorflow.serving.Model.ModelSpec getModelSpec() {
        if (modelSpecBuilder_ == null) {
          return modelSpec_ == null ? tensorflow.serving.Model.ModelSpec.getDefaultInstance() : modelSpec_;
        } else {
          return modelSpecBuilder_.getMessage();
        }
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder setModelSpec(tensorflow.serving.Model.ModelSpec value) {
        if (modelSpecBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          modelSpec_ = value;
          onChanged();
        } else {
          modelSpecBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder setModelSpec(
          tensorflow.serving.Model.ModelSpec.Builder builderForValue) {
        if (modelSpecBuilder_ == null) {
          modelSpec_ = builderForValue.build();
          onChanged();
        } else {
          modelSpecBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder mergeModelSpec(tensorflow.serving.Model.ModelSpec value) {
        if (modelSpecBuilder_ == null) {
          if (modelSpec_ != null) {
            modelSpec_ =
              tensorflow.serving.Model.ModelSpec.newBuilder(modelSpec_).mergeFrom(value).buildPartial();
          } else {
            modelSpec_ = value;
          }
          onChanged();
        } else {
          modelSpecBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public Builder clearModelSpec() {
        if (modelSpecBuilder_ == null) {
          modelSpec_ = null;
          onChanged();
        } else {
          modelSpec_ = null;
          modelSpecBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public tensorflow.serving.Model.ModelSpec.Builder getModelSpecBuilder() {
        
        onChanged();
        return getModelSpecFieldBuilder().getBuilder();
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      public tensorflow.serving.Model.ModelSpecOrBuilder getModelSpecOrBuilder() {
        if (modelSpecBuilder_ != null) {
          return modelSpecBuilder_.getMessageOrBuilder();
        } else {
          return modelSpec_ == null ?
              tensorflow.serving.Model.ModelSpec.getDefaultInstance() : modelSpec_;
        }
      }
      /**
       * <code>.tensorflow.serving.ModelSpec model_spec = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tensorflow.serving.Model.ModelSpec, tensorflow.serving.Model.ModelSpec.Builder, tensorflow.serving.Model.ModelSpecOrBuilder> 
          getModelSpecFieldBuilder() {
        if (modelSpecBuilder_ == null) {
          modelSpecBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tensorflow.serving.Model.ModelSpec, tensorflow.serving.Model.ModelSpec.Builder, tensorflow.serving.Model.ModelSpecOrBuilder>(
                  getModelSpec(),
                  getParentForChildren(),
                  isClean());
          modelSpec_ = null;
        }
        return modelSpecBuilder_;
      }

      private tensorflow.serving.LoggingConfigOuterClass.SamplingConfig samplingConfig_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tensorflow.serving.LoggingConfigOuterClass.SamplingConfig, tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.Builder, tensorflow.serving.LoggingConfigOuterClass.SamplingConfigOrBuilder> samplingConfigBuilder_;
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       * @return Whether the samplingConfig field is set.
       */
      public boolean hasSamplingConfig() {
        return samplingConfigBuilder_ != null || samplingConfig_ != null;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       * @return The samplingConfig.
       */
      public tensorflow.serving.LoggingConfigOuterClass.SamplingConfig getSamplingConfig() {
        if (samplingConfigBuilder_ == null) {
          return samplingConfig_ == null ? tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.getDefaultInstance() : samplingConfig_;
        } else {
          return samplingConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public Builder setSamplingConfig(tensorflow.serving.LoggingConfigOuterClass.SamplingConfig value) {
        if (samplingConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          samplingConfig_ = value;
          onChanged();
        } else {
          samplingConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public Builder setSamplingConfig(
          tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.Builder builderForValue) {
        if (samplingConfigBuilder_ == null) {
          samplingConfig_ = builderForValue.build();
          onChanged();
        } else {
          samplingConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public Builder mergeSamplingConfig(tensorflow.serving.LoggingConfigOuterClass.SamplingConfig value) {
        if (samplingConfigBuilder_ == null) {
          if (samplingConfig_ != null) {
            samplingConfig_ =
              tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.newBuilder(samplingConfig_).mergeFrom(value).buildPartial();
          } else {
            samplingConfig_ = value;
          }
          onChanged();
        } else {
          samplingConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public Builder clearSamplingConfig() {
        if (samplingConfigBuilder_ == null) {
          samplingConfig_ = null;
          onChanged();
        } else {
          samplingConfig_ = null;
          samplingConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.Builder getSamplingConfigBuilder() {
        
        onChanged();
        return getSamplingConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      public tensorflow.serving.LoggingConfigOuterClass.SamplingConfigOrBuilder getSamplingConfigOrBuilder() {
        if (samplingConfigBuilder_ != null) {
          return samplingConfigBuilder_.getMessageOrBuilder();
        } else {
          return samplingConfig_ == null ?
              tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.getDefaultInstance() : samplingConfig_;
        }
      }
      /**
       * <code>.tensorflow.serving.SamplingConfig sampling_config = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tensorflow.serving.LoggingConfigOuterClass.SamplingConfig, tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.Builder, tensorflow.serving.LoggingConfigOuterClass.SamplingConfigOrBuilder> 
          getSamplingConfigFieldBuilder() {
        if (samplingConfigBuilder_ == null) {
          samplingConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tensorflow.serving.LoggingConfigOuterClass.SamplingConfig, tensorflow.serving.LoggingConfigOuterClass.SamplingConfig.Builder, tensorflow.serving.LoggingConfigOuterClass.SamplingConfigOrBuilder>(
                  getSamplingConfig(),
                  getParentForChildren(),
                  isClean());
          samplingConfig_ = null;
        }
        return samplingConfigBuilder_;
      }

      private com.google.protobuf.LazyStringList savedModelTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSavedModelTagsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          savedModelTags_ = new com.google.protobuf.LazyStringArrayList(savedModelTags_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @return A list containing the savedModelTags.
       */
      public com.google.protobuf.ProtocolStringList
          getSavedModelTagsList() {
        return savedModelTags_.getUnmodifiableView();
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @return The count of savedModelTags.
       */
      public int getSavedModelTagsCount() {
        return savedModelTags_.size();
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @param index The index of the element to return.
       * @return The savedModelTags at the given index.
       */
      public java.lang.String getSavedModelTags(int index) {
        return savedModelTags_.get(index);
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the savedModelTags at the given index.
       */
      public com.google.protobuf.ByteString
          getSavedModelTagsBytes(int index) {
        return savedModelTags_.getByteString(index);
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @param index The index to set the value at.
       * @param value The savedModelTags to set.
       * @return This builder for chaining.
       */
      public Builder setSavedModelTags(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSavedModelTagsIsMutable();
        savedModelTags_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @param value The savedModelTags to add.
       * @return This builder for chaining.
       */
      public Builder addSavedModelTags(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSavedModelTagsIsMutable();
        savedModelTags_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @param values The savedModelTags to add.
       * @return This builder for chaining.
       */
      public Builder addAllSavedModelTags(
          java.lang.Iterable<java.lang.String> values) {
        ensureSavedModelTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, savedModelTags_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSavedModelTags() {
        savedModelTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of tags used to load the relevant MetaGraphDef from SavedModel.
       * </pre>
       *
       * <code>repeated string saved_model_tags = 3;</code>
       * @param value The bytes of the savedModelTags to add.
       * @return This builder for chaining.
       */
      public Builder addSavedModelTagsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSavedModelTagsIsMutable();
        savedModelTags_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.LogMetadata)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.LogMetadata)
    private static final tensorflow.serving.Logging.LogMetadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tensorflow.serving.Logging.LogMetadata();
    }

    public static tensorflow.serving.Logging.LogMetadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogMetadata>
        PARSER = new com.google.protobuf.AbstractParser<LogMetadata>() {
      @java.lang.Override
      public LogMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogMetadata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogMetadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogMetadata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tensorflow.serving.Logging.LogMetadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_LogMetadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_LogMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%tensorflow_serving/core/logging.proto\022" +
      "\022tensorflow.serving\032#tensorflow_serving/" +
      "apis/model.proto\032.tensorflow_serving/con" +
      "fig/logging_config.proto\"\227\001\n\013LogMetadata" +
      "\0221\n\nmodel_spec\030\001 \001(\0132\035.tensorflow.servin" +
      "g.ModelSpec\022;\n\017sampling_config\030\002 \001(\0132\".t" +
      "ensorflow.serving.SamplingConfig\022\030\n\020save" +
      "d_model_tags\030\003 \003(\tB\003\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tensorflow.serving.Model.getDescriptor(),
          tensorflow.serving.LoggingConfigOuterClass.getDescriptor(),
        });
    internal_static_tensorflow_serving_LogMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_serving_LogMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_LogMetadata_descriptor,
        new java.lang.String[] { "ModelSpec", "SamplingConfig", "SavedModelTags", });
    tensorflow.serving.Model.getDescriptor();
    tensorflow.serving.LoggingConfigOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
