// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/config.proto

package org.tensorflow.framework;

public interface RPCOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.RPCOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * If true, always use RPC to contact the session target.
   * If false (the default option), TensorFlow may use an optimized
   * transport for client-master communication that avoids the RPC
   * stack. This option is primarily for used testing the RPC stack.
   * </pre>
   *
   * <code>bool use_rpc_for_inprocess_master = 1;</code>
   * @return The useRpcForInprocessMaster.
   */
  boolean getUseRpcForInprocessMaster();

  /**
   * <pre>
   * The compression algorithm to be used. One of "deflate", "gzip".
   * </pre>
   *
   * <code>string compression_algorithm = 2;</code>
   * @return The compressionAlgorithm.
   */
  java.lang.String getCompressionAlgorithm();
  /**
   * <pre>
   * The compression algorithm to be used. One of "deflate", "gzip".
   * </pre>
   *
   * <code>string compression_algorithm = 2;</code>
   * @return The bytes for compressionAlgorithm.
   */
  com.google.protobuf.ByteString
      getCompressionAlgorithmBytes();

  /**
   * <pre>
   * If compression_algorithm is set, the compression level to be used.
   * From 0 (no compression), up to 3.
   * </pre>
   *
   * <code>int32 compression_level = 3;</code>
   * @return The compressionLevel.
   */
  int getCompressionLevel();
}
