// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow_serving/apis/model.proto

package tensorflow.serving;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ModelSpecOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.serving.ModelSpec)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Required servable name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * Required servable name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Use this specific version number.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value version = 2;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <pre>
     * Use this specific version number.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value version = 2;</code>
     * @return The version.
     */
    com.google.protobuf.Int64Value getVersion();
    /**
     * <pre>
     * Use this specific version number.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value version = 2;</code>
     */
    com.google.protobuf.Int64ValueOrBuilder getVersionOrBuilder();

    /**
     * <pre>
     * Use the version associated with the given label.
     * </pre>
     *
     * <code>string version_label = 4;</code>
     * @return The versionLabel.
     */
    java.lang.String getVersionLabel();
    /**
     * <pre>
     * Use the version associated with the given label.
     * </pre>
     *
     * <code>string version_label = 4;</code>
     * @return The bytes for versionLabel.
     */
    com.google.protobuf.ByteString
        getVersionLabelBytes();

    /**
     * <pre>
     * A named signature to evaluate. If unspecified, the default signature will
     * be used.
     * </pre>
     *
     * <code>string signature_name = 3;</code>
     * @return The signatureName.
     */
    java.lang.String getSignatureName();
    /**
     * <pre>
     * A named signature to evaluate. If unspecified, the default signature will
     * be used.
     * </pre>
     *
     * <code>string signature_name = 3;</code>
     * @return The bytes for signatureName.
     */
    com.google.protobuf.ByteString
        getSignatureNameBytes();

    public tensorflow.serving.Model.ModelSpec.VersionChoiceCase getVersionChoiceCase();
  }
  /**
   * <pre>
   * Metadata for an inference request such as the model name and version.
   * </pre>
   *
   * Protobuf type {@code tensorflow.serving.ModelSpec}
   */
  public  static final class ModelSpec extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tensorflow.serving.ModelSpec)
      ModelSpecOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ModelSpec.newBuilder() to construct.
    private ModelSpec(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ModelSpec() {
      name_ = "";
      signatureName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ModelSpec();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ModelSpec(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.Int64Value.Builder subBuilder = null;
              if (versionChoiceCase_ == 2) {
                subBuilder = ((com.google.protobuf.Int64Value) versionChoice_).toBuilder();
              }
              versionChoice_ =
                  input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.google.protobuf.Int64Value) versionChoice_);
                versionChoice_ = subBuilder.buildPartial();
              }
              versionChoiceCase_ = 2;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              signatureName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              versionChoiceCase_ = 4;
              versionChoice_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tensorflow.serving.Model.internal_static_tensorflow_serving_ModelSpec_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tensorflow.serving.Model.internal_static_tensorflow_serving_ModelSpec_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tensorflow.serving.Model.ModelSpec.class, tensorflow.serving.Model.ModelSpec.Builder.class);
    }

    private int versionChoiceCase_ = 0;
    private java.lang.Object versionChoice_;
    public enum VersionChoiceCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      VERSION(2),
      VERSION_LABEL(4),
      VERSIONCHOICE_NOT_SET(0);
      private final int value;
      private VersionChoiceCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static VersionChoiceCase valueOf(int value) {
        return forNumber(value);
      }

      public static VersionChoiceCase forNumber(int value) {
        switch (value) {
          case 2: return VERSION;
          case 4: return VERSION_LABEL;
          case 0: return VERSIONCHOICE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public VersionChoiceCase
    getVersionChoiceCase() {
      return VersionChoiceCase.forNumber(
          versionChoiceCase_);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * Required servable name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Required servable name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    /**
     * <pre>
     * Use this specific version number.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value version = 2;</code>
     * @return Whether the version field is set.
     */
    public boolean hasVersion() {
      return versionChoiceCase_ == 2;
    }
    /**
     * <pre>
     * Use this specific version number.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value version = 2;</code>
     * @return The version.
     */
    public com.google.protobuf.Int64Value getVersion() {
      if (versionChoiceCase_ == 2) {
         return (com.google.protobuf.Int64Value) versionChoice_;
      }
      return com.google.protobuf.Int64Value.getDefaultInstance();
    }
    /**
     * <pre>
     * Use this specific version number.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value version = 2;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getVersionOrBuilder() {
      if (versionChoiceCase_ == 2) {
         return (com.google.protobuf.Int64Value) versionChoice_;
      }
      return com.google.protobuf.Int64Value.getDefaultInstance();
    }

    public static final int VERSION_LABEL_FIELD_NUMBER = 4;
    /**
     * <pre>
     * Use the version associated with the given label.
     * </pre>
     *
     * <code>string version_label = 4;</code>
     * @return The versionLabel.
     */
    public java.lang.String getVersionLabel() {
      java.lang.Object ref = "";
      if (versionChoiceCase_ == 4) {
        ref = versionChoice_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (versionChoiceCase_ == 4) {
          versionChoice_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Use the version associated with the given label.
     * </pre>
     *
     * <code>string version_label = 4;</code>
     * @return The bytes for versionLabel.
     */
    public com.google.protobuf.ByteString
        getVersionLabelBytes() {
      java.lang.Object ref = "";
      if (versionChoiceCase_ == 4) {
        ref = versionChoice_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (versionChoiceCase_ == 4) {
          versionChoice_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATURE_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object signatureName_;
    /**
     * <pre>
     * A named signature to evaluate. If unspecified, the default signature will
     * be used.
     * </pre>
     *
     * <code>string signature_name = 3;</code>
     * @return The signatureName.
     */
    public java.lang.String getSignatureName() {
      java.lang.Object ref = signatureName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signatureName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * A named signature to evaluate. If unspecified, the default signature will
     * be used.
     * </pre>
     *
     * <code>string signature_name = 3;</code>
     * @return The bytes for signatureName.
     */
    public com.google.protobuf.ByteString
        getSignatureNameBytes() {
      java.lang.Object ref = signatureName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signatureName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (versionChoiceCase_ == 2) {
        output.writeMessage(2, (com.google.protobuf.Int64Value) versionChoice_);
      }
      if (!getSignatureNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, signatureName_);
      }
      if (versionChoiceCase_ == 4) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, versionChoice_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (versionChoiceCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.google.protobuf.Int64Value) versionChoice_);
      }
      if (!getSignatureNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, signatureName_);
      }
      if (versionChoiceCase_ == 4) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, versionChoice_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tensorflow.serving.Model.ModelSpec)) {
        return super.equals(obj);
      }
      tensorflow.serving.Model.ModelSpec other = (tensorflow.serving.Model.ModelSpec) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getSignatureName()
          .equals(other.getSignatureName())) return false;
      if (!getVersionChoiceCase().equals(other.getVersionChoiceCase())) return false;
      switch (versionChoiceCase_) {
        case 2:
          if (!getVersion()
              .equals(other.getVersion())) return false;
          break;
        case 4:
          if (!getVersionLabel()
              .equals(other.getVersionLabel())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SIGNATURE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSignatureName().hashCode();
      switch (versionChoiceCase_) {
        case 2:
          hash = (37 * hash) + VERSION_FIELD_NUMBER;
          hash = (53 * hash) + getVersion().hashCode();
          break;
        case 4:
          hash = (37 * hash) + VERSION_LABEL_FIELD_NUMBER;
          hash = (53 * hash) + getVersionLabel().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tensorflow.serving.Model.ModelSpec parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.Model.ModelSpec parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.Model.ModelSpec parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.Model.ModelSpec parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.Model.ModelSpec parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.serving.Model.ModelSpec parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.serving.Model.ModelSpec parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.serving.Model.ModelSpec parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tensorflow.serving.Model.ModelSpec parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tensorflow.serving.Model.ModelSpec parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tensorflow.serving.Model.ModelSpec parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tensorflow.serving.Model.ModelSpec parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tensorflow.serving.Model.ModelSpec prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Metadata for an inference request such as the model name and version.
     * </pre>
     *
     * Protobuf type {@code tensorflow.serving.ModelSpec}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.serving.ModelSpec)
        tensorflow.serving.Model.ModelSpecOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tensorflow.serving.Model.internal_static_tensorflow_serving_ModelSpec_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tensorflow.serving.Model.internal_static_tensorflow_serving_ModelSpec_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tensorflow.serving.Model.ModelSpec.class, tensorflow.serving.Model.ModelSpec.Builder.class);
      }

      // Construct using tensorflow.serving.Model.ModelSpec.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        signatureName_ = "";

        versionChoiceCase_ = 0;
        versionChoice_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tensorflow.serving.Model.internal_static_tensorflow_serving_ModelSpec_descriptor;
      }

      @java.lang.Override
      public tensorflow.serving.Model.ModelSpec getDefaultInstanceForType() {
        return tensorflow.serving.Model.ModelSpec.getDefaultInstance();
      }

      @java.lang.Override
      public tensorflow.serving.Model.ModelSpec build() {
        tensorflow.serving.Model.ModelSpec result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tensorflow.serving.Model.ModelSpec buildPartial() {
        tensorflow.serving.Model.ModelSpec result = new tensorflow.serving.Model.ModelSpec(this);
        result.name_ = name_;
        if (versionChoiceCase_ == 2) {
          if (versionBuilder_ == null) {
            result.versionChoice_ = versionChoice_;
          } else {
            result.versionChoice_ = versionBuilder_.build();
          }
        }
        if (versionChoiceCase_ == 4) {
          result.versionChoice_ = versionChoice_;
        }
        result.signatureName_ = signatureName_;
        result.versionChoiceCase_ = versionChoiceCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tensorflow.serving.Model.ModelSpec) {
          return mergeFrom((tensorflow.serving.Model.ModelSpec)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tensorflow.serving.Model.ModelSpec other) {
        if (other == tensorflow.serving.Model.ModelSpec.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getSignatureName().isEmpty()) {
          signatureName_ = other.signatureName_;
          onChanged();
        }
        switch (other.getVersionChoiceCase()) {
          case VERSION: {
            mergeVersion(other.getVersion());
            break;
          }
          case VERSION_LABEL: {
            versionChoiceCase_ = 4;
            versionChoice_ = other.versionChoice_;
            onChanged();
            break;
          }
          case VERSIONCHOICE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tensorflow.serving.Model.ModelSpec parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tensorflow.serving.Model.ModelSpec) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int versionChoiceCase_ = 0;
      private java.lang.Object versionChoice_;
      public VersionChoiceCase
          getVersionChoiceCase() {
        return VersionChoiceCase.forNumber(
            versionChoiceCase_);
      }

      public Builder clearVersionChoice() {
        versionChoiceCase_ = 0;
        versionChoice_ = null;
        onChanged();
        return this;
      }


      private java.lang.Object name_ = "";
      /**
       * <pre>
       * Required servable name.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Required servable name.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Required servable name.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Required servable name.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Required servable name.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> versionBuilder_;
      /**
       * <pre>
       * Use this specific version number.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value version = 2;</code>
       * @return Whether the version field is set.
       */
      public boolean hasVersion() {
        return versionChoiceCase_ == 2;
      }
      /**
       * <pre>
       * Use this specific version number.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value version = 2;</code>
       * @return The version.
       */
      public com.google.protobuf.Int64Value getVersion() {
        if (versionBuilder_ == null) {
          if (versionChoiceCase_ == 2) {
            return (com.google.protobuf.Int64Value) versionChoice_;
          }
          return com.google.protobuf.Int64Value.getDefaultInstance();
        } else {
          if (versionChoiceCase_ == 2) {
            return versionBuilder_.getMessage();
          }
          return com.google.protobuf.Int64Value.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Use this specific version number.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value version = 2;</code>
       */
      public Builder setVersion(com.google.protobuf.Int64Value value) {
        if (versionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          versionChoice_ = value;
          onChanged();
        } else {
          versionBuilder_.setMessage(value);
        }
        versionChoiceCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * Use this specific version number.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value version = 2;</code>
       */
      public Builder setVersion(
          com.google.protobuf.Int64Value.Builder builderForValue) {
        if (versionBuilder_ == null) {
          versionChoice_ = builderForValue.build();
          onChanged();
        } else {
          versionBuilder_.setMessage(builderForValue.build());
        }
        versionChoiceCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * Use this specific version number.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value version = 2;</code>
       */
      public Builder mergeVersion(com.google.protobuf.Int64Value value) {
        if (versionBuilder_ == null) {
          if (versionChoiceCase_ == 2 &&
              versionChoice_ != com.google.protobuf.Int64Value.getDefaultInstance()) {
            versionChoice_ = com.google.protobuf.Int64Value.newBuilder((com.google.protobuf.Int64Value) versionChoice_)
                .mergeFrom(value).buildPartial();
          } else {
            versionChoice_ = value;
          }
          onChanged();
        } else {
          if (versionChoiceCase_ == 2) {
            versionBuilder_.mergeFrom(value);
          }
          versionBuilder_.setMessage(value);
        }
        versionChoiceCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * Use this specific version number.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value version = 2;</code>
       */
      public Builder clearVersion() {
        if (versionBuilder_ == null) {
          if (versionChoiceCase_ == 2) {
            versionChoiceCase_ = 0;
            versionChoice_ = null;
            onChanged();
          }
        } else {
          if (versionChoiceCase_ == 2) {
            versionChoiceCase_ = 0;
            versionChoice_ = null;
          }
          versionBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Use this specific version number.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value version = 2;</code>
       */
      public com.google.protobuf.Int64Value.Builder getVersionBuilder() {
        return getVersionFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Use this specific version number.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value version = 2;</code>
       */
      public com.google.protobuf.Int64ValueOrBuilder getVersionOrBuilder() {
        if ((versionChoiceCase_ == 2) && (versionBuilder_ != null)) {
          return versionBuilder_.getMessageOrBuilder();
        } else {
          if (versionChoiceCase_ == 2) {
            return (com.google.protobuf.Int64Value) versionChoice_;
          }
          return com.google.protobuf.Int64Value.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Use this specific version number.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value version = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
          getVersionFieldBuilder() {
        if (versionBuilder_ == null) {
          if (!(versionChoiceCase_ == 2)) {
            versionChoice_ = com.google.protobuf.Int64Value.getDefaultInstance();
          }
          versionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                  (com.google.protobuf.Int64Value) versionChoice_,
                  getParentForChildren(),
                  isClean());
          versionChoice_ = null;
        }
        versionChoiceCase_ = 2;
        onChanged();;
        return versionBuilder_;
      }

      /**
       * <pre>
       * Use the version associated with the given label.
       * </pre>
       *
       * <code>string version_label = 4;</code>
       * @return The versionLabel.
       */
      public java.lang.String getVersionLabel() {
        java.lang.Object ref = "";
        if (versionChoiceCase_ == 4) {
          ref = versionChoice_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (versionChoiceCase_ == 4) {
            versionChoice_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Use the version associated with the given label.
       * </pre>
       *
       * <code>string version_label = 4;</code>
       * @return The bytes for versionLabel.
       */
      public com.google.protobuf.ByteString
          getVersionLabelBytes() {
        java.lang.Object ref = "";
        if (versionChoiceCase_ == 4) {
          ref = versionChoice_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (versionChoiceCase_ == 4) {
            versionChoice_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Use the version associated with the given label.
       * </pre>
       *
       * <code>string version_label = 4;</code>
       * @param value The versionLabel to set.
       * @return This builder for chaining.
       */
      public Builder setVersionLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  versionChoiceCase_ = 4;
        versionChoice_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Use the version associated with the given label.
       * </pre>
       *
       * <code>string version_label = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersionLabel() {
        if (versionChoiceCase_ == 4) {
          versionChoiceCase_ = 0;
          versionChoice_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Use the version associated with the given label.
       * </pre>
       *
       * <code>string version_label = 4;</code>
       * @param value The bytes for versionLabel to set.
       * @return This builder for chaining.
       */
      public Builder setVersionLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        versionChoiceCase_ = 4;
        versionChoice_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object signatureName_ = "";
      /**
       * <pre>
       * A named signature to evaluate. If unspecified, the default signature will
       * be used.
       * </pre>
       *
       * <code>string signature_name = 3;</code>
       * @return The signatureName.
       */
      public java.lang.String getSignatureName() {
        java.lang.Object ref = signatureName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signatureName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * A named signature to evaluate. If unspecified, the default signature will
       * be used.
       * </pre>
       *
       * <code>string signature_name = 3;</code>
       * @return The bytes for signatureName.
       */
      public com.google.protobuf.ByteString
          getSignatureNameBytes() {
        java.lang.Object ref = signatureName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signatureName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * A named signature to evaluate. If unspecified, the default signature will
       * be used.
       * </pre>
       *
       * <code>string signature_name = 3;</code>
       * @param value The signatureName to set.
       * @return This builder for chaining.
       */
      public Builder setSignatureName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signatureName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A named signature to evaluate. If unspecified, the default signature will
       * be used.
       * </pre>
       *
       * <code>string signature_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignatureName() {
        
        signatureName_ = getDefaultInstance().getSignatureName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A named signature to evaluate. If unspecified, the default signature will
       * be used.
       * </pre>
       *
       * <code>string signature_name = 3;</code>
       * @param value The bytes for signatureName to set.
       * @return This builder for chaining.
       */
      public Builder setSignatureNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signatureName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.serving.ModelSpec)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.serving.ModelSpec)
    private static final tensorflow.serving.Model.ModelSpec DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tensorflow.serving.Model.ModelSpec();
    }

    public static tensorflow.serving.Model.ModelSpec getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ModelSpec>
        PARSER = new com.google.protobuf.AbstractParser<ModelSpec>() {
      @java.lang.Override
      public ModelSpec parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ModelSpec(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ModelSpec> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ModelSpec> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tensorflow.serving.Model.ModelSpec getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_ModelSpec_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_ModelSpec_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#tensorflow_serving/apis/model.proto\022\022t" +
      "ensorflow.serving\032\036google/protobuf/wrapp" +
      "ers.proto\"\214\001\n\tModelSpec\022\014\n\004name\030\001 \001(\t\022.\n" +
      "\007version\030\002 \001(\0132\033.google.protobuf.Int64Va" +
      "lueH\000\022\027\n\rversion_label\030\004 \001(\tH\000\022\026\n\016signat" +
      "ure_name\030\003 \001(\tB\020\n\016version_choiceB\003\370\001\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_tensorflow_serving_ModelSpec_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_serving_ModelSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_ModelSpec_descriptor,
        new java.lang.String[] { "Name", "Version", "VersionLabel", "SignatureName", "VersionChoice", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
