// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker.proto

package org.tensorflow.distruntime;

/**
 * <pre>
 * Options specific to the execution of a single step.
 * </pre>
 *
 * Protobuf type {@code tensorflow.ExecutorOpts}
 */
public  final class ExecutorOpts extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.ExecutorOpts)
    ExecutorOptsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecutorOpts.newBuilder() to construct.
  private ExecutorOpts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecutorOpts() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecutorOpts();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExecutorOpts(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            recordCosts_ = input.readBool();
            break;
          }
          case 24: {

            recordTimeline_ = input.readBool();
            break;
          }
          case 32: {

            recordPartitionGraphs_ = input.readBool();
            break;
          }
          case 40: {

            reportTensorAllocationsUponOom_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_ExecutorOpts_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_ExecutorOpts_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.distruntime.ExecutorOpts.class, org.tensorflow.distruntime.ExecutorOpts.Builder.class);
  }

  public static final int RECORD_COSTS_FIELD_NUMBER = 1;
  private boolean recordCosts_;
  /**
   * <code>bool record_costs = 1;</code>
   * @return The recordCosts.
   */
  public boolean getRecordCosts() {
    return recordCosts_;
  }

  public static final int RECORD_TIMELINE_FIELD_NUMBER = 3;
  private boolean recordTimeline_;
  /**
   * <code>bool record_timeline = 3;</code>
   * @return The recordTimeline.
   */
  public boolean getRecordTimeline() {
    return recordTimeline_;
  }

  public static final int RECORD_PARTITION_GRAPHS_FIELD_NUMBER = 4;
  private boolean recordPartitionGraphs_;
  /**
   * <code>bool record_partition_graphs = 4;</code>
   * @return The recordPartitionGraphs.
   */
  public boolean getRecordPartitionGraphs() {
    return recordPartitionGraphs_;
  }

  public static final int REPORT_TENSOR_ALLOCATIONS_UPON_OOM_FIELD_NUMBER = 5;
  private boolean reportTensorAllocationsUponOom_;
  /**
   * <code>bool report_tensor_allocations_upon_oom = 5;</code>
   * @return The reportTensorAllocationsUponOom.
   */
  public boolean getReportTensorAllocationsUponOom() {
    return reportTensorAllocationsUponOom_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (recordCosts_ != false) {
      output.writeBool(1, recordCosts_);
    }
    if (recordTimeline_ != false) {
      output.writeBool(3, recordTimeline_);
    }
    if (recordPartitionGraphs_ != false) {
      output.writeBool(4, recordPartitionGraphs_);
    }
    if (reportTensorAllocationsUponOom_ != false) {
      output.writeBool(5, reportTensorAllocationsUponOom_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (recordCosts_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, recordCosts_);
    }
    if (recordTimeline_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, recordTimeline_);
    }
    if (recordPartitionGraphs_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, recordPartitionGraphs_);
    }
    if (reportTensorAllocationsUponOom_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, reportTensorAllocationsUponOom_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tensorflow.distruntime.ExecutorOpts)) {
      return super.equals(obj);
    }
    org.tensorflow.distruntime.ExecutorOpts other = (org.tensorflow.distruntime.ExecutorOpts) obj;

    if (getRecordCosts()
        != other.getRecordCosts()) return false;
    if (getRecordTimeline()
        != other.getRecordTimeline()) return false;
    if (getRecordPartitionGraphs()
        != other.getRecordPartitionGraphs()) return false;
    if (getReportTensorAllocationsUponOom()
        != other.getReportTensorAllocationsUponOom()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RECORD_COSTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRecordCosts());
    hash = (37 * hash) + RECORD_TIMELINE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRecordTimeline());
    hash = (37 * hash) + RECORD_PARTITION_GRAPHS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRecordPartitionGraphs());
    hash = (37 * hash) + REPORT_TENSOR_ALLOCATIONS_UPON_OOM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getReportTensorAllocationsUponOom());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tensorflow.distruntime.ExecutorOpts parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.ExecutorOpts parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.ExecutorOpts parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.ExecutorOpts parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.ExecutorOpts parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.ExecutorOpts parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.ExecutorOpts parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.ExecutorOpts parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.distruntime.ExecutorOpts parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.ExecutorOpts parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.distruntime.ExecutorOpts parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.ExecutorOpts parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.distruntime.ExecutorOpts prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Options specific to the execution of a single step.
   * </pre>
   *
   * Protobuf type {@code tensorflow.ExecutorOpts}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.ExecutorOpts)
      org.tensorflow.distruntime.ExecutorOptsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_ExecutorOpts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_ExecutorOpts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.distruntime.ExecutorOpts.class, org.tensorflow.distruntime.ExecutorOpts.Builder.class);
    }

    // Construct using org.tensorflow.distruntime.ExecutorOpts.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      recordCosts_ = false;

      recordTimeline_ = false;

      recordPartitionGraphs_ = false;

      reportTensorAllocationsUponOom_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_ExecutorOpts_descriptor;
    }

    @java.lang.Override
    public org.tensorflow.distruntime.ExecutorOpts getDefaultInstanceForType() {
      return org.tensorflow.distruntime.ExecutorOpts.getDefaultInstance();
    }

    @java.lang.Override
    public org.tensorflow.distruntime.ExecutorOpts build() {
      org.tensorflow.distruntime.ExecutorOpts result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.tensorflow.distruntime.ExecutorOpts buildPartial() {
      org.tensorflow.distruntime.ExecutorOpts result = new org.tensorflow.distruntime.ExecutorOpts(this);
      result.recordCosts_ = recordCosts_;
      result.recordTimeline_ = recordTimeline_;
      result.recordPartitionGraphs_ = recordPartitionGraphs_;
      result.reportTensorAllocationsUponOom_ = reportTensorAllocationsUponOom_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.distruntime.ExecutorOpts) {
        return mergeFrom((org.tensorflow.distruntime.ExecutorOpts)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.distruntime.ExecutorOpts other) {
      if (other == org.tensorflow.distruntime.ExecutorOpts.getDefaultInstance()) return this;
      if (other.getRecordCosts() != false) {
        setRecordCosts(other.getRecordCosts());
      }
      if (other.getRecordTimeline() != false) {
        setRecordTimeline(other.getRecordTimeline());
      }
      if (other.getRecordPartitionGraphs() != false) {
        setRecordPartitionGraphs(other.getRecordPartitionGraphs());
      }
      if (other.getReportTensorAllocationsUponOom() != false) {
        setReportTensorAllocationsUponOom(other.getReportTensorAllocationsUponOom());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.distruntime.ExecutorOpts parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.distruntime.ExecutorOpts) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean recordCosts_ ;
    /**
     * <code>bool record_costs = 1;</code>
     * @return The recordCosts.
     */
    public boolean getRecordCosts() {
      return recordCosts_;
    }
    /**
     * <code>bool record_costs = 1;</code>
     * @param value The recordCosts to set.
     * @return This builder for chaining.
     */
    public Builder setRecordCosts(boolean value) {
      
      recordCosts_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool record_costs = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecordCosts() {
      
      recordCosts_ = false;
      onChanged();
      return this;
    }

    private boolean recordTimeline_ ;
    /**
     * <code>bool record_timeline = 3;</code>
     * @return The recordTimeline.
     */
    public boolean getRecordTimeline() {
      return recordTimeline_;
    }
    /**
     * <code>bool record_timeline = 3;</code>
     * @param value The recordTimeline to set.
     * @return This builder for chaining.
     */
    public Builder setRecordTimeline(boolean value) {
      
      recordTimeline_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool record_timeline = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecordTimeline() {
      
      recordTimeline_ = false;
      onChanged();
      return this;
    }

    private boolean recordPartitionGraphs_ ;
    /**
     * <code>bool record_partition_graphs = 4;</code>
     * @return The recordPartitionGraphs.
     */
    public boolean getRecordPartitionGraphs() {
      return recordPartitionGraphs_;
    }
    /**
     * <code>bool record_partition_graphs = 4;</code>
     * @param value The recordPartitionGraphs to set.
     * @return This builder for chaining.
     */
    public Builder setRecordPartitionGraphs(boolean value) {
      
      recordPartitionGraphs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool record_partition_graphs = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecordPartitionGraphs() {
      
      recordPartitionGraphs_ = false;
      onChanged();
      return this;
    }

    private boolean reportTensorAllocationsUponOom_ ;
    /**
     * <code>bool report_tensor_allocations_upon_oom = 5;</code>
     * @return The reportTensorAllocationsUponOom.
     */
    public boolean getReportTensorAllocationsUponOom() {
      return reportTensorAllocationsUponOom_;
    }
    /**
     * <code>bool report_tensor_allocations_upon_oom = 5;</code>
     * @param value The reportTensorAllocationsUponOom to set.
     * @return This builder for chaining.
     */
    public Builder setReportTensorAllocationsUponOom(boolean value) {
      
      reportTensorAllocationsUponOom_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool report_tensor_allocations_upon_oom = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearReportTensorAllocationsUponOom() {
      
      reportTensorAllocationsUponOom_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.ExecutorOpts)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.ExecutorOpts)
  private static final org.tensorflow.distruntime.ExecutorOpts DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.distruntime.ExecutorOpts();
  }

  public static org.tensorflow.distruntime.ExecutorOpts getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecutorOpts>
      PARSER = new com.google.protobuf.AbstractParser<ExecutorOpts>() {
    @java.lang.Override
    public ExecutorOpts parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExecutorOpts(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExecutorOpts> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecutorOpts> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.tensorflow.distruntime.ExecutorOpts getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

