// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/master.proto

package org.tensorflow.distruntime;

/**
 * Protobuf type {@code tensorflow.PartialRunSetupRequest}
 */
public  final class PartialRunSetupRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.PartialRunSetupRequest)
    PartialRunSetupRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PartialRunSetupRequest.newBuilder() to construct.
  private PartialRunSetupRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PartialRunSetupRequest() {
    sessionHandle_ = "";
    feed_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    fetch_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    target_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PartialRunSetupRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PartialRunSetupRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            sessionHandle_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              feed_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            feed_.add(s);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              fetch_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            fetch_.add(s);
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              target_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            target_.add(s);
            break;
          }
          case 40: {

            requestId_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        feed_ = feed_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        fetch_ = fetch_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        target_ = target_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.distruntime.DistributedRuntimeProtos.internal_static_tensorflow_PartialRunSetupRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.distruntime.DistributedRuntimeProtos.internal_static_tensorflow_PartialRunSetupRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.distruntime.PartialRunSetupRequest.class, org.tensorflow.distruntime.PartialRunSetupRequest.Builder.class);
  }

  public static final int SESSION_HANDLE_FIELD_NUMBER = 1;
  private volatile java.lang.Object sessionHandle_;
  /**
   * <pre>
   * REQUIRED: session_handle must be returned by a CreateSession call
   * to the same master service.
   * </pre>
   *
   * <code>string session_handle = 1;</code>
   * @return The sessionHandle.
   */
  public java.lang.String getSessionHandle() {
    java.lang.Object ref = sessionHandle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionHandle_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * REQUIRED: session_handle must be returned by a CreateSession call
   * to the same master service.
   * </pre>
   *
   * <code>string session_handle = 1;</code>
   * @return The bytes for sessionHandle.
   */
  public com.google.protobuf.ByteString
      getSessionHandleBytes() {
    java.lang.Object ref = sessionHandle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionHandle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FEED_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList feed_;
  /**
   * <pre>
   * Tensors to be fed in future steps.
   * </pre>
   *
   * <code>repeated string feed = 2;</code>
   * @return A list containing the feed.
   */
  public com.google.protobuf.ProtocolStringList
      getFeedList() {
    return feed_;
  }
  /**
   * <pre>
   * Tensors to be fed in future steps.
   * </pre>
   *
   * <code>repeated string feed = 2;</code>
   * @return The count of feed.
   */
  public int getFeedCount() {
    return feed_.size();
  }
  /**
   * <pre>
   * Tensors to be fed in future steps.
   * </pre>
   *
   * <code>repeated string feed = 2;</code>
   * @param index The index of the element to return.
   * @return The feed at the given index.
   */
  public java.lang.String getFeed(int index) {
    return feed_.get(index);
  }
  /**
   * <pre>
   * Tensors to be fed in future steps.
   * </pre>
   *
   * <code>repeated string feed = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the feed at the given index.
   */
  public com.google.protobuf.ByteString
      getFeedBytes(int index) {
    return feed_.getByteString(index);
  }

  public static final int FETCH_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList fetch_;
  /**
   * <pre>
   * Fetches. A list of tensor names. The caller expects a tensor to be returned
   * for each fetch[i] (see RunStepResponse.tensor), for corresponding partial
   * RunStepRequests. The order of specified fetches does not change the
   * execution order.
   * </pre>
   *
   * <code>repeated string fetch = 3;</code>
   * @return A list containing the fetch.
   */
  public com.google.protobuf.ProtocolStringList
      getFetchList() {
    return fetch_;
  }
  /**
   * <pre>
   * Fetches. A list of tensor names. The caller expects a tensor to be returned
   * for each fetch[i] (see RunStepResponse.tensor), for corresponding partial
   * RunStepRequests. The order of specified fetches does not change the
   * execution order.
   * </pre>
   *
   * <code>repeated string fetch = 3;</code>
   * @return The count of fetch.
   */
  public int getFetchCount() {
    return fetch_.size();
  }
  /**
   * <pre>
   * Fetches. A list of tensor names. The caller expects a tensor to be returned
   * for each fetch[i] (see RunStepResponse.tensor), for corresponding partial
   * RunStepRequests. The order of specified fetches does not change the
   * execution order.
   * </pre>
   *
   * <code>repeated string fetch = 3;</code>
   * @param index The index of the element to return.
   * @return The fetch at the given index.
   */
  public java.lang.String getFetch(int index) {
    return fetch_.get(index);
  }
  /**
   * <pre>
   * Fetches. A list of tensor names. The caller expects a tensor to be returned
   * for each fetch[i] (see RunStepResponse.tensor), for corresponding partial
   * RunStepRequests. The order of specified fetches does not change the
   * execution order.
   * </pre>
   *
   * <code>repeated string fetch = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the fetch at the given index.
   */
  public com.google.protobuf.ByteString
      getFetchBytes(int index) {
    return fetch_.getByteString(index);
  }

  public static final int TARGET_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList target_;
  /**
   * <pre>
   * Target Nodes. A list of node names. The named nodes will be run in future
   * steps, but their outputs will not be fetched.
   * </pre>
   *
   * <code>repeated string target = 4;</code>
   * @return A list containing the target.
   */
  public com.google.protobuf.ProtocolStringList
      getTargetList() {
    return target_;
  }
  /**
   * <pre>
   * Target Nodes. A list of node names. The named nodes will be run in future
   * steps, but their outputs will not be fetched.
   * </pre>
   *
   * <code>repeated string target = 4;</code>
   * @return The count of target.
   */
  public int getTargetCount() {
    return target_.size();
  }
  /**
   * <pre>
   * Target Nodes. A list of node names. The named nodes will be run in future
   * steps, but their outputs will not be fetched.
   * </pre>
   *
   * <code>repeated string target = 4;</code>
   * @param index The index of the element to return.
   * @return The target at the given index.
   */
  public java.lang.String getTarget(int index) {
    return target_.get(index);
  }
  /**
   * <pre>
   * Target Nodes. A list of node names. The named nodes will be run in future
   * steps, but their outputs will not be fetched.
   * </pre>
   *
   * <code>repeated string target = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the target at the given index.
   */
  public com.google.protobuf.ByteString
      getTargetBytes(int index) {
    return target_.getByteString(index);
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 5;
  private long requestId_;
  /**
   * <pre>
   * Unique identifier for this request. Every PartialRunSetupRequest must
   * have a unique request_id, and retried PartialRunSetupRequest must have
   * the same request_id. If request_id is zero, retry detection is disabled.
   * </pre>
   *
   * <code>int64 request_id = 5;</code>
   * @return The requestId.
   */
  public long getRequestId() {
    return requestId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSessionHandleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sessionHandle_);
    }
    for (int i = 0; i < feed_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, feed_.getRaw(i));
    }
    for (int i = 0; i < fetch_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fetch_.getRaw(i));
    }
    for (int i = 0; i < target_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, target_.getRaw(i));
    }
    if (requestId_ != 0L) {
      output.writeInt64(5, requestId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSessionHandleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sessionHandle_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < feed_.size(); i++) {
        dataSize += computeStringSizeNoTag(feed_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFeedList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < fetch_.size(); i++) {
        dataSize += computeStringSizeNoTag(fetch_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFetchList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < target_.size(); i++) {
        dataSize += computeStringSizeNoTag(target_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTargetList().size();
    }
    if (requestId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, requestId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tensorflow.distruntime.PartialRunSetupRequest)) {
      return super.equals(obj);
    }
    org.tensorflow.distruntime.PartialRunSetupRequest other = (org.tensorflow.distruntime.PartialRunSetupRequest) obj;

    if (!getSessionHandle()
        .equals(other.getSessionHandle())) return false;
    if (!getFeedList()
        .equals(other.getFeedList())) return false;
    if (!getFetchList()
        .equals(other.getFetchList())) return false;
    if (!getTargetList()
        .equals(other.getTargetList())) return false;
    if (getRequestId()
        != other.getRequestId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_HANDLE_FIELD_NUMBER;
    hash = (53 * hash) + getSessionHandle().hashCode();
    if (getFeedCount() > 0) {
      hash = (37 * hash) + FEED_FIELD_NUMBER;
      hash = (53 * hash) + getFeedList().hashCode();
    }
    if (getFetchCount() > 0) {
      hash = (37 * hash) + FETCH_FIELD_NUMBER;
      hash = (53 * hash) + getFetchList().hashCode();
    }
    if (getTargetCount() > 0) {
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTargetList().hashCode();
    }
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRequestId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tensorflow.distruntime.PartialRunSetupRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.PartialRunSetupRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.PartialRunSetupRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.PartialRunSetupRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.PartialRunSetupRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.PartialRunSetupRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.PartialRunSetupRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.PartialRunSetupRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.distruntime.PartialRunSetupRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.PartialRunSetupRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.distruntime.PartialRunSetupRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.PartialRunSetupRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.distruntime.PartialRunSetupRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.PartialRunSetupRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.PartialRunSetupRequest)
      org.tensorflow.distruntime.PartialRunSetupRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.distruntime.DistributedRuntimeProtos.internal_static_tensorflow_PartialRunSetupRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.distruntime.DistributedRuntimeProtos.internal_static_tensorflow_PartialRunSetupRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.distruntime.PartialRunSetupRequest.class, org.tensorflow.distruntime.PartialRunSetupRequest.Builder.class);
    }

    // Construct using org.tensorflow.distruntime.PartialRunSetupRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sessionHandle_ = "";

      feed_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      fetch_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      target_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      requestId_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.distruntime.DistributedRuntimeProtos.internal_static_tensorflow_PartialRunSetupRequest_descriptor;
    }

    @java.lang.Override
    public org.tensorflow.distruntime.PartialRunSetupRequest getDefaultInstanceForType() {
      return org.tensorflow.distruntime.PartialRunSetupRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.tensorflow.distruntime.PartialRunSetupRequest build() {
      org.tensorflow.distruntime.PartialRunSetupRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.tensorflow.distruntime.PartialRunSetupRequest buildPartial() {
      org.tensorflow.distruntime.PartialRunSetupRequest result = new org.tensorflow.distruntime.PartialRunSetupRequest(this);
      int from_bitField0_ = bitField0_;
      result.sessionHandle_ = sessionHandle_;
      if (((bitField0_ & 0x00000001) != 0)) {
        feed_ = feed_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.feed_ = feed_;
      if (((bitField0_ & 0x00000002) != 0)) {
        fetch_ = fetch_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.fetch_ = fetch_;
      if (((bitField0_ & 0x00000004) != 0)) {
        target_ = target_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.target_ = target_;
      result.requestId_ = requestId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.distruntime.PartialRunSetupRequest) {
        return mergeFrom((org.tensorflow.distruntime.PartialRunSetupRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.distruntime.PartialRunSetupRequest other) {
      if (other == org.tensorflow.distruntime.PartialRunSetupRequest.getDefaultInstance()) return this;
      if (!other.getSessionHandle().isEmpty()) {
        sessionHandle_ = other.sessionHandle_;
        onChanged();
      }
      if (!other.feed_.isEmpty()) {
        if (feed_.isEmpty()) {
          feed_ = other.feed_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureFeedIsMutable();
          feed_.addAll(other.feed_);
        }
        onChanged();
      }
      if (!other.fetch_.isEmpty()) {
        if (fetch_.isEmpty()) {
          fetch_ = other.fetch_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureFetchIsMutable();
          fetch_.addAll(other.fetch_);
        }
        onChanged();
      }
      if (!other.target_.isEmpty()) {
        if (target_.isEmpty()) {
          target_ = other.target_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureTargetIsMutable();
          target_.addAll(other.target_);
        }
        onChanged();
      }
      if (other.getRequestId() != 0L) {
        setRequestId(other.getRequestId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.distruntime.PartialRunSetupRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.distruntime.PartialRunSetupRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionHandle_ = "";
    /**
     * <pre>
     * REQUIRED: session_handle must be returned by a CreateSession call
     * to the same master service.
     * </pre>
     *
     * <code>string session_handle = 1;</code>
     * @return The sessionHandle.
     */
    public java.lang.String getSessionHandle() {
      java.lang.Object ref = sessionHandle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionHandle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * REQUIRED: session_handle must be returned by a CreateSession call
     * to the same master service.
     * </pre>
     *
     * <code>string session_handle = 1;</code>
     * @return The bytes for sessionHandle.
     */
    public com.google.protobuf.ByteString
        getSessionHandleBytes() {
      java.lang.Object ref = sessionHandle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionHandle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * REQUIRED: session_handle must be returned by a CreateSession call
     * to the same master service.
     * </pre>
     *
     * <code>string session_handle = 1;</code>
     * @param value The sessionHandle to set.
     * @return This builder for chaining.
     */
    public Builder setSessionHandle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sessionHandle_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * REQUIRED: session_handle must be returned by a CreateSession call
     * to the same master service.
     * </pre>
     *
     * <code>string session_handle = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionHandle() {
      
      sessionHandle_ = getDefaultInstance().getSessionHandle();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * REQUIRED: session_handle must be returned by a CreateSession call
     * to the same master service.
     * </pre>
     *
     * <code>string session_handle = 1;</code>
     * @param value The bytes for sessionHandle to set.
     * @return This builder for chaining.
     */
    public Builder setSessionHandleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sessionHandle_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList feed_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFeedIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        feed_ = new com.google.protobuf.LazyStringArrayList(feed_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * Tensors to be fed in future steps.
     * </pre>
     *
     * <code>repeated string feed = 2;</code>
     * @return A list containing the feed.
     */
    public com.google.protobuf.ProtocolStringList
        getFeedList() {
      return feed_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Tensors to be fed in future steps.
     * </pre>
     *
     * <code>repeated string feed = 2;</code>
     * @return The count of feed.
     */
    public int getFeedCount() {
      return feed_.size();
    }
    /**
     * <pre>
     * Tensors to be fed in future steps.
     * </pre>
     *
     * <code>repeated string feed = 2;</code>
     * @param index The index of the element to return.
     * @return The feed at the given index.
     */
    public java.lang.String getFeed(int index) {
      return feed_.get(index);
    }
    /**
     * <pre>
     * Tensors to be fed in future steps.
     * </pre>
     *
     * <code>repeated string feed = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the feed at the given index.
     */
    public com.google.protobuf.ByteString
        getFeedBytes(int index) {
      return feed_.getByteString(index);
    }
    /**
     * <pre>
     * Tensors to be fed in future steps.
     * </pre>
     *
     * <code>repeated string feed = 2;</code>
     * @param index The index to set the value at.
     * @param value The feed to set.
     * @return This builder for chaining.
     */
    public Builder setFeed(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFeedIsMutable();
      feed_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tensors to be fed in future steps.
     * </pre>
     *
     * <code>repeated string feed = 2;</code>
     * @param value The feed to add.
     * @return This builder for chaining.
     */
    public Builder addFeed(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFeedIsMutable();
      feed_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tensors to be fed in future steps.
     * </pre>
     *
     * <code>repeated string feed = 2;</code>
     * @param values The feed to add.
     * @return This builder for chaining.
     */
    public Builder addAllFeed(
        java.lang.Iterable<java.lang.String> values) {
      ensureFeedIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, feed_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tensors to be fed in future steps.
     * </pre>
     *
     * <code>repeated string feed = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFeed() {
      feed_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tensors to be fed in future steps.
     * </pre>
     *
     * <code>repeated string feed = 2;</code>
     * @param value The bytes of the feed to add.
     * @return This builder for chaining.
     */
    public Builder addFeedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFeedIsMutable();
      feed_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList fetch_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFetchIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        fetch_ = new com.google.protobuf.LazyStringArrayList(fetch_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to be returned
     * for each fetch[i] (see RunStepResponse.tensor), for corresponding partial
     * RunStepRequests. The order of specified fetches does not change the
     * execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     * @return A list containing the fetch.
     */
    public com.google.protobuf.ProtocolStringList
        getFetchList() {
      return fetch_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to be returned
     * for each fetch[i] (see RunStepResponse.tensor), for corresponding partial
     * RunStepRequests. The order of specified fetches does not change the
     * execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     * @return The count of fetch.
     */
    public int getFetchCount() {
      return fetch_.size();
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to be returned
     * for each fetch[i] (see RunStepResponse.tensor), for corresponding partial
     * RunStepRequests. The order of specified fetches does not change the
     * execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     * @param index The index of the element to return.
     * @return The fetch at the given index.
     */
    public java.lang.String getFetch(int index) {
      return fetch_.get(index);
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to be returned
     * for each fetch[i] (see RunStepResponse.tensor), for corresponding partial
     * RunStepRequests. The order of specified fetches does not change the
     * execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the fetch at the given index.
     */
    public com.google.protobuf.ByteString
        getFetchBytes(int index) {
      return fetch_.getByteString(index);
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to be returned
     * for each fetch[i] (see RunStepResponse.tensor), for corresponding partial
     * RunStepRequests. The order of specified fetches does not change the
     * execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     * @param index The index to set the value at.
     * @param value The fetch to set.
     * @return This builder for chaining.
     */
    public Builder setFetch(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFetchIsMutable();
      fetch_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to be returned
     * for each fetch[i] (see RunStepResponse.tensor), for corresponding partial
     * RunStepRequests. The order of specified fetches does not change the
     * execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     * @param value The fetch to add.
     * @return This builder for chaining.
     */
    public Builder addFetch(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFetchIsMutable();
      fetch_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to be returned
     * for each fetch[i] (see RunStepResponse.tensor), for corresponding partial
     * RunStepRequests. The order of specified fetches does not change the
     * execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     * @param values The fetch to add.
     * @return This builder for chaining.
     */
    public Builder addAllFetch(
        java.lang.Iterable<java.lang.String> values) {
      ensureFetchIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, fetch_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to be returned
     * for each fetch[i] (see RunStepResponse.tensor), for corresponding partial
     * RunStepRequests. The order of specified fetches does not change the
     * execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFetch() {
      fetch_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to be returned
     * for each fetch[i] (see RunStepResponse.tensor), for corresponding partial
     * RunStepRequests. The order of specified fetches does not change the
     * execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     * @param value The bytes of the fetch to add.
     * @return This builder for chaining.
     */
    public Builder addFetchBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFetchIsMutable();
      fetch_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList target_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTargetIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        target_ = new com.google.protobuf.LazyStringArrayList(target_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run in future
     * steps, but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     * @return A list containing the target.
     */
    public com.google.protobuf.ProtocolStringList
        getTargetList() {
      return target_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run in future
     * steps, but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     * @return The count of target.
     */
    public int getTargetCount() {
      return target_.size();
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run in future
     * steps, but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     * @param index The index of the element to return.
     * @return The target at the given index.
     */
    public java.lang.String getTarget(int index) {
      return target_.get(index);
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run in future
     * steps, but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the target at the given index.
     */
    public com.google.protobuf.ByteString
        getTargetBytes(int index) {
      return target_.getByteString(index);
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run in future
     * steps, but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     * @param index The index to set the value at.
     * @param value The target to set.
     * @return This builder for chaining.
     */
    public Builder setTarget(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetIsMutable();
      target_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run in future
     * steps, but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     * @param value The target to add.
     * @return This builder for chaining.
     */
    public Builder addTarget(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetIsMutable();
      target_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run in future
     * steps, but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     * @param values The target to add.
     * @return This builder for chaining.
     */
    public Builder addAllTarget(
        java.lang.Iterable<java.lang.String> values) {
      ensureTargetIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, target_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run in future
     * steps, but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTarget() {
      target_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run in future
     * steps, but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     * @param value The bytes of the target to add.
     * @return This builder for chaining.
     */
    public Builder addTargetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTargetIsMutable();
      target_.add(value);
      onChanged();
      return this;
    }

    private long requestId_ ;
    /**
     * <pre>
     * Unique identifier for this request. Every PartialRunSetupRequest must
     * have a unique request_id, and retried PartialRunSetupRequest must have
     * the same request_id. If request_id is zero, retry detection is disabled.
     * </pre>
     *
     * <code>int64 request_id = 5;</code>
     * @return The requestId.
     */
    public long getRequestId() {
      return requestId_;
    }
    /**
     * <pre>
     * Unique identifier for this request. Every PartialRunSetupRequest must
     * have a unique request_id, and retried PartialRunSetupRequest must have
     * the same request_id. If request_id is zero, retry detection is disabled.
     * </pre>
     *
     * <code>int64 request_id = 5;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(long value) {
      
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier for this request. Every PartialRunSetupRequest must
     * have a unique request_id, and retried PartialRunSetupRequest must have
     * the same request_id. If request_id is zero, retry detection is disabled.
     * </pre>
     *
     * <code>int64 request_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      
      requestId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.PartialRunSetupRequest)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.PartialRunSetupRequest)
  private static final org.tensorflow.distruntime.PartialRunSetupRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.distruntime.PartialRunSetupRequest();
  }

  public static org.tensorflow.distruntime.PartialRunSetupRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PartialRunSetupRequest>
      PARSER = new com.google.protobuf.AbstractParser<PartialRunSetupRequest>() {
    @java.lang.Override
    public PartialRunSetupRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PartialRunSetupRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PartialRunSetupRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PartialRunSetupRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.tensorflow.distruntime.PartialRunSetupRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

