// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker.proto

package org.tensorflow.distruntime;

/**
 * <pre>
 * Use of the fields below may vary by implementation.  For example
 * the buf_ptr and num_bytes may be set only for local operations and
 * not sent on the wire, or only sent on the wire in one direction.
 * </pre>
 *
 * Protobuf type {@code tensorflow.RecvBufRequest}
 */
public  final class RecvBufRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.RecvBufRequest)
    RecvBufRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecvBufRequest.newBuilder() to construct.
  private RecvBufRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecvBufRequest() {
    bufRendezvousKey_ = "";
    srcDevice_ = "";
    dstDevice_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RecvBufRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RecvBufRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            stepId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            bufRendezvousKey_ = s;
            break;
          }
          case 24: {

            numBytes_ = input.readInt64();
            break;
          }
          case 33: {

            bufPtr_ = input.readFixed64();
            break;
          }
          case 42: {
            org.tensorflow.framework.DeviceLocality.Builder subBuilder = null;
            if (clientLocality_ != null) {
              subBuilder = clientLocality_.toBuilder();
            }
            clientLocality_ = input.readMessage(org.tensorflow.framework.DeviceLocality.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(clientLocality_);
              clientLocality_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            org.tensorflow.framework.DeviceLocality.Builder subBuilder = null;
            if (serverLocality_ != null) {
              subBuilder = serverLocality_.toBuilder();
            }
            serverLocality_ = input.readMessage(org.tensorflow.framework.DeviceLocality.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(serverLocality_);
              serverLocality_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.Any.Builder subBuilder = null;
            if (transportOptions_ != null) {
              subBuilder = transportOptions_.toBuilder();
            }
            transportOptions_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(transportOptions_);
              transportOptions_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            srcDevice_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            dstDevice_ = s;
            break;
          }
          case 80: {

            requestId_ = input.readInt64();
            break;
          }
          case 88: {

            srcIncarnation_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_RecvBufRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_RecvBufRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.distruntime.RecvBufRequest.class, org.tensorflow.distruntime.RecvBufRequest.Builder.class);
  }

  public static final int STEP_ID_FIELD_NUMBER = 1;
  private long stepId_;
  /**
   * <pre>
   * Used at server side to find the correct BufRendezvous.
   * </pre>
   *
   * <code>int64 step_id = 1;</code>
   * @return The stepId.
   */
  public long getStepId() {
    return stepId_;
  }

  public static final int BUF_RENDEZVOUS_KEY_FIELD_NUMBER = 2;
  private volatile java.lang.Object bufRendezvousKey_;
  /**
   * <pre>
   * Arbitrary string identifying a BufRendezvous entry.
   * </pre>
   *
   * <code>string buf_rendezvous_key = 2;</code>
   * @return The bufRendezvousKey.
   */
  public java.lang.String getBufRendezvousKey() {
    java.lang.Object ref = bufRendezvousKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bufRendezvousKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Arbitrary string identifying a BufRendezvous entry.
   * </pre>
   *
   * <code>string buf_rendezvous_key = 2;</code>
   * @return The bytes for bufRendezvousKey.
   */
  public com.google.protobuf.ByteString
      getBufRendezvousKeyBytes() {
    java.lang.Object ref = bufRendezvousKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bufRendezvousKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUM_BYTES_FIELD_NUMBER = 3;
  private long numBytes_;
  /**
   * <pre>
   * Size of value expected, must agree with BufRendezvous entry.
   * </pre>
   *
   * <code>int64 num_bytes = 3;</code>
   * @return The numBytes.
   */
  public long getNumBytes() {
    return numBytes_;
  }

  public static final int BUF_PTR_FIELD_NUMBER = 4;
  private long bufPtr_;
  /**
   * <pre>
   * When RDMA is in use, address of destination field on client.
   * </pre>
   *
   * <code>fixed64 buf_ptr = 4;</code>
   * @return The bufPtr.
   */
  public long getBufPtr() {
    return bufPtr_;
  }

  public static final int CLIENT_LOCALITY_FIELD_NUMBER = 5;
  private org.tensorflow.framework.DeviceLocality clientLocality_;
  /**
   * <pre>
   * Optional information on client-side device locality.
   * </pre>
   *
   * <code>.tensorflow.DeviceLocality client_locality = 5;</code>
   * @return Whether the clientLocality field is set.
   */
  public boolean hasClientLocality() {
    return clientLocality_ != null;
  }
  /**
   * <pre>
   * Optional information on client-side device locality.
   * </pre>
   *
   * <code>.tensorflow.DeviceLocality client_locality = 5;</code>
   * @return The clientLocality.
   */
  public org.tensorflow.framework.DeviceLocality getClientLocality() {
    return clientLocality_ == null ? org.tensorflow.framework.DeviceLocality.getDefaultInstance() : clientLocality_;
  }
  /**
   * <pre>
   * Optional information on client-side device locality.
   * </pre>
   *
   * <code>.tensorflow.DeviceLocality client_locality = 5;</code>
   */
  public org.tensorflow.framework.DeviceLocalityOrBuilder getClientLocalityOrBuilder() {
    return getClientLocality();
  }

  public static final int SERVER_LOCALITY_FIELD_NUMBER = 6;
  private org.tensorflow.framework.DeviceLocality serverLocality_;
  /**
   * <pre>
   * Optional information on server-side device locality.
   * </pre>
   *
   * <code>.tensorflow.DeviceLocality server_locality = 6;</code>
   * @return Whether the serverLocality field is set.
   */
  public boolean hasServerLocality() {
    return serverLocality_ != null;
  }
  /**
   * <pre>
   * Optional information on server-side device locality.
   * </pre>
   *
   * <code>.tensorflow.DeviceLocality server_locality = 6;</code>
   * @return The serverLocality.
   */
  public org.tensorflow.framework.DeviceLocality getServerLocality() {
    return serverLocality_ == null ? org.tensorflow.framework.DeviceLocality.getDefaultInstance() : serverLocality_;
  }
  /**
   * <pre>
   * Optional information on server-side device locality.
   * </pre>
   *
   * <code>.tensorflow.DeviceLocality server_locality = 6;</code>
   */
  public org.tensorflow.framework.DeviceLocalityOrBuilder getServerLocalityOrBuilder() {
    return getServerLocality();
  }

  public static final int TRANSPORT_OPTIONS_FIELD_NUMBER = 7;
  private com.google.protobuf.Any transportOptions_;
  /**
   * <pre>
   * Optional, implementation-specific data.
   * </pre>
   *
   * <code>.google.protobuf.Any transport_options = 7;</code>
   * @return Whether the transportOptions field is set.
   */
  public boolean hasTransportOptions() {
    return transportOptions_ != null;
  }
  /**
   * <pre>
   * Optional, implementation-specific data.
   * </pre>
   *
   * <code>.google.protobuf.Any transport_options = 7;</code>
   * @return The transportOptions.
   */
  public com.google.protobuf.Any getTransportOptions() {
    return transportOptions_ == null ? com.google.protobuf.Any.getDefaultInstance() : transportOptions_;
  }
  /**
   * <pre>
   * Optional, implementation-specific data.
   * </pre>
   *
   * <code>.google.protobuf.Any transport_options = 7;</code>
   */
  public com.google.protobuf.AnyOrBuilder getTransportOptionsOrBuilder() {
    return getTransportOptions();
  }

  public static final int SRC_DEVICE_FIELD_NUMBER = 8;
  private volatile java.lang.Object srcDevice_;
  /**
   * <pre>
   * For annotating timeline and device incarnation check.
   * </pre>
   *
   * <code>string src_device = 8;</code>
   * @return The srcDevice.
   */
  public java.lang.String getSrcDevice() {
    java.lang.Object ref = srcDevice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      srcDevice_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * For annotating timeline and device incarnation check.
   * </pre>
   *
   * <code>string src_device = 8;</code>
   * @return The bytes for srcDevice.
   */
  public com.google.protobuf.ByteString
      getSrcDeviceBytes() {
    java.lang.Object ref = srcDevice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      srcDevice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DST_DEVICE_FIELD_NUMBER = 9;
  private volatile java.lang.Object dstDevice_;
  /**
   * <pre>
   * Optional, for annotating the timeline.
   * </pre>
   *
   * <code>string dst_device = 9;</code>
   * @return The dstDevice.
   */
  public java.lang.String getDstDevice() {
    java.lang.Object ref = dstDevice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dstDevice_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional, for annotating the timeline.
   * </pre>
   *
   * <code>string dst_device = 9;</code>
   * @return The bytes for dstDevice.
   */
  public com.google.protobuf.ByteString
      getDstDeviceBytes() {
    java.lang.Object ref = dstDevice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dstDevice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 10;
  private long requestId_;
  /**
   * <pre>
   * Depending on the RPC system in use, it may be necessary to set this
   * id to detect resends of RPCs where the server is not aware that
   * the prior RPC failed.
   * </pre>
   *
   * <code>int64 request_id = 10;</code>
   * @return The requestId.
   */
  public long getRequestId() {
    return requestId_;
  }

  public static final int SRC_INCARNATION_FIELD_NUMBER = 11;
  private long srcIncarnation_;
  /**
   * <pre>
   * Incarnation number of the source device, used to detect worker failures.
   * </pre>
   *
   * <code>uint64 src_incarnation = 11;</code>
   * @return The srcIncarnation.
   */
  public long getSrcIncarnation() {
    return srcIncarnation_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stepId_ != 0L) {
      output.writeInt64(1, stepId_);
    }
    if (!getBufRendezvousKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bufRendezvousKey_);
    }
    if (numBytes_ != 0L) {
      output.writeInt64(3, numBytes_);
    }
    if (bufPtr_ != 0L) {
      output.writeFixed64(4, bufPtr_);
    }
    if (clientLocality_ != null) {
      output.writeMessage(5, getClientLocality());
    }
    if (serverLocality_ != null) {
      output.writeMessage(6, getServerLocality());
    }
    if (transportOptions_ != null) {
      output.writeMessage(7, getTransportOptions());
    }
    if (!getSrcDeviceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, srcDevice_);
    }
    if (!getDstDeviceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, dstDevice_);
    }
    if (requestId_ != 0L) {
      output.writeInt64(10, requestId_);
    }
    if (srcIncarnation_ != 0L) {
      output.writeUInt64(11, srcIncarnation_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (stepId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, stepId_);
    }
    if (!getBufRendezvousKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bufRendezvousKey_);
    }
    if (numBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, numBytes_);
    }
    if (bufPtr_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(4, bufPtr_);
    }
    if (clientLocality_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getClientLocality());
    }
    if (serverLocality_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getServerLocality());
    }
    if (transportOptions_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getTransportOptions());
    }
    if (!getSrcDeviceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, srcDevice_);
    }
    if (!getDstDeviceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, dstDevice_);
    }
    if (requestId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, requestId_);
    }
    if (srcIncarnation_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(11, srcIncarnation_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tensorflow.distruntime.RecvBufRequest)) {
      return super.equals(obj);
    }
    org.tensorflow.distruntime.RecvBufRequest other = (org.tensorflow.distruntime.RecvBufRequest) obj;

    if (getStepId()
        != other.getStepId()) return false;
    if (!getBufRendezvousKey()
        .equals(other.getBufRendezvousKey())) return false;
    if (getNumBytes()
        != other.getNumBytes()) return false;
    if (getBufPtr()
        != other.getBufPtr()) return false;
    if (hasClientLocality() != other.hasClientLocality()) return false;
    if (hasClientLocality()) {
      if (!getClientLocality()
          .equals(other.getClientLocality())) return false;
    }
    if (hasServerLocality() != other.hasServerLocality()) return false;
    if (hasServerLocality()) {
      if (!getServerLocality()
          .equals(other.getServerLocality())) return false;
    }
    if (hasTransportOptions() != other.hasTransportOptions()) return false;
    if (hasTransportOptions()) {
      if (!getTransportOptions()
          .equals(other.getTransportOptions())) return false;
    }
    if (!getSrcDevice()
        .equals(other.getSrcDevice())) return false;
    if (!getDstDevice()
        .equals(other.getDstDevice())) return false;
    if (getRequestId()
        != other.getRequestId()) return false;
    if (getSrcIncarnation()
        != other.getSrcIncarnation()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STEP_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStepId());
    hash = (37 * hash) + BUF_RENDEZVOUS_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getBufRendezvousKey().hashCode();
    hash = (37 * hash) + NUM_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumBytes());
    hash = (37 * hash) + BUF_PTR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBufPtr());
    if (hasClientLocality()) {
      hash = (37 * hash) + CLIENT_LOCALITY_FIELD_NUMBER;
      hash = (53 * hash) + getClientLocality().hashCode();
    }
    if (hasServerLocality()) {
      hash = (37 * hash) + SERVER_LOCALITY_FIELD_NUMBER;
      hash = (53 * hash) + getServerLocality().hashCode();
    }
    if (hasTransportOptions()) {
      hash = (37 * hash) + TRANSPORT_OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getTransportOptions().hashCode();
    }
    hash = (37 * hash) + SRC_DEVICE_FIELD_NUMBER;
    hash = (53 * hash) + getSrcDevice().hashCode();
    hash = (37 * hash) + DST_DEVICE_FIELD_NUMBER;
    hash = (53 * hash) + getDstDevice().hashCode();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRequestId());
    hash = (37 * hash) + SRC_INCARNATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSrcIncarnation());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tensorflow.distruntime.RecvBufRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.RecvBufRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RecvBufRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.RecvBufRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RecvBufRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.RecvBufRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RecvBufRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.RecvBufRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RecvBufRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.RecvBufRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RecvBufRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.RecvBufRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.distruntime.RecvBufRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Use of the fields below may vary by implementation.  For example
   * the buf_ptr and num_bytes may be set only for local operations and
   * not sent on the wire, or only sent on the wire in one direction.
   * </pre>
   *
   * Protobuf type {@code tensorflow.RecvBufRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.RecvBufRequest)
      org.tensorflow.distruntime.RecvBufRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_RecvBufRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_RecvBufRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.distruntime.RecvBufRequest.class, org.tensorflow.distruntime.RecvBufRequest.Builder.class);
    }

    // Construct using org.tensorflow.distruntime.RecvBufRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      stepId_ = 0L;

      bufRendezvousKey_ = "";

      numBytes_ = 0L;

      bufPtr_ = 0L;

      if (clientLocalityBuilder_ == null) {
        clientLocality_ = null;
      } else {
        clientLocality_ = null;
        clientLocalityBuilder_ = null;
      }
      if (serverLocalityBuilder_ == null) {
        serverLocality_ = null;
      } else {
        serverLocality_ = null;
        serverLocalityBuilder_ = null;
      }
      if (transportOptionsBuilder_ == null) {
        transportOptions_ = null;
      } else {
        transportOptions_ = null;
        transportOptionsBuilder_ = null;
      }
      srcDevice_ = "";

      dstDevice_ = "";

      requestId_ = 0L;

      srcIncarnation_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_RecvBufRequest_descriptor;
    }

    @java.lang.Override
    public org.tensorflow.distruntime.RecvBufRequest getDefaultInstanceForType() {
      return org.tensorflow.distruntime.RecvBufRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.tensorflow.distruntime.RecvBufRequest build() {
      org.tensorflow.distruntime.RecvBufRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.tensorflow.distruntime.RecvBufRequest buildPartial() {
      org.tensorflow.distruntime.RecvBufRequest result = new org.tensorflow.distruntime.RecvBufRequest(this);
      result.stepId_ = stepId_;
      result.bufRendezvousKey_ = bufRendezvousKey_;
      result.numBytes_ = numBytes_;
      result.bufPtr_ = bufPtr_;
      if (clientLocalityBuilder_ == null) {
        result.clientLocality_ = clientLocality_;
      } else {
        result.clientLocality_ = clientLocalityBuilder_.build();
      }
      if (serverLocalityBuilder_ == null) {
        result.serverLocality_ = serverLocality_;
      } else {
        result.serverLocality_ = serverLocalityBuilder_.build();
      }
      if (transportOptionsBuilder_ == null) {
        result.transportOptions_ = transportOptions_;
      } else {
        result.transportOptions_ = transportOptionsBuilder_.build();
      }
      result.srcDevice_ = srcDevice_;
      result.dstDevice_ = dstDevice_;
      result.requestId_ = requestId_;
      result.srcIncarnation_ = srcIncarnation_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.distruntime.RecvBufRequest) {
        return mergeFrom((org.tensorflow.distruntime.RecvBufRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.distruntime.RecvBufRequest other) {
      if (other == org.tensorflow.distruntime.RecvBufRequest.getDefaultInstance()) return this;
      if (other.getStepId() != 0L) {
        setStepId(other.getStepId());
      }
      if (!other.getBufRendezvousKey().isEmpty()) {
        bufRendezvousKey_ = other.bufRendezvousKey_;
        onChanged();
      }
      if (other.getNumBytes() != 0L) {
        setNumBytes(other.getNumBytes());
      }
      if (other.getBufPtr() != 0L) {
        setBufPtr(other.getBufPtr());
      }
      if (other.hasClientLocality()) {
        mergeClientLocality(other.getClientLocality());
      }
      if (other.hasServerLocality()) {
        mergeServerLocality(other.getServerLocality());
      }
      if (other.hasTransportOptions()) {
        mergeTransportOptions(other.getTransportOptions());
      }
      if (!other.getSrcDevice().isEmpty()) {
        srcDevice_ = other.srcDevice_;
        onChanged();
      }
      if (!other.getDstDevice().isEmpty()) {
        dstDevice_ = other.dstDevice_;
        onChanged();
      }
      if (other.getRequestId() != 0L) {
        setRequestId(other.getRequestId());
      }
      if (other.getSrcIncarnation() != 0L) {
        setSrcIncarnation(other.getSrcIncarnation());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.distruntime.RecvBufRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.distruntime.RecvBufRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long stepId_ ;
    /**
     * <pre>
     * Used at server side to find the correct BufRendezvous.
     * </pre>
     *
     * <code>int64 step_id = 1;</code>
     * @return The stepId.
     */
    public long getStepId() {
      return stepId_;
    }
    /**
     * <pre>
     * Used at server side to find the correct BufRendezvous.
     * </pre>
     *
     * <code>int64 step_id = 1;</code>
     * @param value The stepId to set.
     * @return This builder for chaining.
     */
    public Builder setStepId(long value) {
      
      stepId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Used at server side to find the correct BufRendezvous.
     * </pre>
     *
     * <code>int64 step_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStepId() {
      
      stepId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object bufRendezvousKey_ = "";
    /**
     * <pre>
     * Arbitrary string identifying a BufRendezvous entry.
     * </pre>
     *
     * <code>string buf_rendezvous_key = 2;</code>
     * @return The bufRendezvousKey.
     */
    public java.lang.String getBufRendezvousKey() {
      java.lang.Object ref = bufRendezvousKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bufRendezvousKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Arbitrary string identifying a BufRendezvous entry.
     * </pre>
     *
     * <code>string buf_rendezvous_key = 2;</code>
     * @return The bytes for bufRendezvousKey.
     */
    public com.google.protobuf.ByteString
        getBufRendezvousKeyBytes() {
      java.lang.Object ref = bufRendezvousKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bufRendezvousKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Arbitrary string identifying a BufRendezvous entry.
     * </pre>
     *
     * <code>string buf_rendezvous_key = 2;</code>
     * @param value The bufRendezvousKey to set.
     * @return This builder for chaining.
     */
    public Builder setBufRendezvousKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bufRendezvousKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Arbitrary string identifying a BufRendezvous entry.
     * </pre>
     *
     * <code>string buf_rendezvous_key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBufRendezvousKey() {
      
      bufRendezvousKey_ = getDefaultInstance().getBufRendezvousKey();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Arbitrary string identifying a BufRendezvous entry.
     * </pre>
     *
     * <code>string buf_rendezvous_key = 2;</code>
     * @param value The bytes for bufRendezvousKey to set.
     * @return This builder for chaining.
     */
    public Builder setBufRendezvousKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bufRendezvousKey_ = value;
      onChanged();
      return this;
    }

    private long numBytes_ ;
    /**
     * <pre>
     * Size of value expected, must agree with BufRendezvous entry.
     * </pre>
     *
     * <code>int64 num_bytes = 3;</code>
     * @return The numBytes.
     */
    public long getNumBytes() {
      return numBytes_;
    }
    /**
     * <pre>
     * Size of value expected, must agree with BufRendezvous entry.
     * </pre>
     *
     * <code>int64 num_bytes = 3;</code>
     * @param value The numBytes to set.
     * @return This builder for chaining.
     */
    public Builder setNumBytes(long value) {
      
      numBytes_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Size of value expected, must agree with BufRendezvous entry.
     * </pre>
     *
     * <code>int64 num_bytes = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumBytes() {
      
      numBytes_ = 0L;
      onChanged();
      return this;
    }

    private long bufPtr_ ;
    /**
     * <pre>
     * When RDMA is in use, address of destination field on client.
     * </pre>
     *
     * <code>fixed64 buf_ptr = 4;</code>
     * @return The bufPtr.
     */
    public long getBufPtr() {
      return bufPtr_;
    }
    /**
     * <pre>
     * When RDMA is in use, address of destination field on client.
     * </pre>
     *
     * <code>fixed64 buf_ptr = 4;</code>
     * @param value The bufPtr to set.
     * @return This builder for chaining.
     */
    public Builder setBufPtr(long value) {
      
      bufPtr_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When RDMA is in use, address of destination field on client.
     * </pre>
     *
     * <code>fixed64 buf_ptr = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBufPtr() {
      
      bufPtr_ = 0L;
      onChanged();
      return this;
    }

    private org.tensorflow.framework.DeviceLocality clientLocality_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tensorflow.framework.DeviceLocality, org.tensorflow.framework.DeviceLocality.Builder, org.tensorflow.framework.DeviceLocalityOrBuilder> clientLocalityBuilder_;
    /**
     * <pre>
     * Optional information on client-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality client_locality = 5;</code>
     * @return Whether the clientLocality field is set.
     */
    public boolean hasClientLocality() {
      return clientLocalityBuilder_ != null || clientLocality_ != null;
    }
    /**
     * <pre>
     * Optional information on client-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality client_locality = 5;</code>
     * @return The clientLocality.
     */
    public org.tensorflow.framework.DeviceLocality getClientLocality() {
      if (clientLocalityBuilder_ == null) {
        return clientLocality_ == null ? org.tensorflow.framework.DeviceLocality.getDefaultInstance() : clientLocality_;
      } else {
        return clientLocalityBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional information on client-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality client_locality = 5;</code>
     */
    public Builder setClientLocality(org.tensorflow.framework.DeviceLocality value) {
      if (clientLocalityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientLocality_ = value;
        onChanged();
      } else {
        clientLocalityBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional information on client-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality client_locality = 5;</code>
     */
    public Builder setClientLocality(
        org.tensorflow.framework.DeviceLocality.Builder builderForValue) {
      if (clientLocalityBuilder_ == null) {
        clientLocality_ = builderForValue.build();
        onChanged();
      } else {
        clientLocalityBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Optional information on client-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality client_locality = 5;</code>
     */
    public Builder mergeClientLocality(org.tensorflow.framework.DeviceLocality value) {
      if (clientLocalityBuilder_ == null) {
        if (clientLocality_ != null) {
          clientLocality_ =
            org.tensorflow.framework.DeviceLocality.newBuilder(clientLocality_).mergeFrom(value).buildPartial();
        } else {
          clientLocality_ = value;
        }
        onChanged();
      } else {
        clientLocalityBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional information on client-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality client_locality = 5;</code>
     */
    public Builder clearClientLocality() {
      if (clientLocalityBuilder_ == null) {
        clientLocality_ = null;
        onChanged();
      } else {
        clientLocality_ = null;
        clientLocalityBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Optional information on client-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality client_locality = 5;</code>
     */
    public org.tensorflow.framework.DeviceLocality.Builder getClientLocalityBuilder() {
      
      onChanged();
      return getClientLocalityFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional information on client-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality client_locality = 5;</code>
     */
    public org.tensorflow.framework.DeviceLocalityOrBuilder getClientLocalityOrBuilder() {
      if (clientLocalityBuilder_ != null) {
        return clientLocalityBuilder_.getMessageOrBuilder();
      } else {
        return clientLocality_ == null ?
            org.tensorflow.framework.DeviceLocality.getDefaultInstance() : clientLocality_;
      }
    }
    /**
     * <pre>
     * Optional information on client-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality client_locality = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tensorflow.framework.DeviceLocality, org.tensorflow.framework.DeviceLocality.Builder, org.tensorflow.framework.DeviceLocalityOrBuilder> 
        getClientLocalityFieldBuilder() {
      if (clientLocalityBuilder_ == null) {
        clientLocalityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.tensorflow.framework.DeviceLocality, org.tensorflow.framework.DeviceLocality.Builder, org.tensorflow.framework.DeviceLocalityOrBuilder>(
                getClientLocality(),
                getParentForChildren(),
                isClean());
        clientLocality_ = null;
      }
      return clientLocalityBuilder_;
    }

    private org.tensorflow.framework.DeviceLocality serverLocality_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tensorflow.framework.DeviceLocality, org.tensorflow.framework.DeviceLocality.Builder, org.tensorflow.framework.DeviceLocalityOrBuilder> serverLocalityBuilder_;
    /**
     * <pre>
     * Optional information on server-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality server_locality = 6;</code>
     * @return Whether the serverLocality field is set.
     */
    public boolean hasServerLocality() {
      return serverLocalityBuilder_ != null || serverLocality_ != null;
    }
    /**
     * <pre>
     * Optional information on server-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality server_locality = 6;</code>
     * @return The serverLocality.
     */
    public org.tensorflow.framework.DeviceLocality getServerLocality() {
      if (serverLocalityBuilder_ == null) {
        return serverLocality_ == null ? org.tensorflow.framework.DeviceLocality.getDefaultInstance() : serverLocality_;
      } else {
        return serverLocalityBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional information on server-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality server_locality = 6;</code>
     */
    public Builder setServerLocality(org.tensorflow.framework.DeviceLocality value) {
      if (serverLocalityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        serverLocality_ = value;
        onChanged();
      } else {
        serverLocalityBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional information on server-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality server_locality = 6;</code>
     */
    public Builder setServerLocality(
        org.tensorflow.framework.DeviceLocality.Builder builderForValue) {
      if (serverLocalityBuilder_ == null) {
        serverLocality_ = builderForValue.build();
        onChanged();
      } else {
        serverLocalityBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Optional information on server-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality server_locality = 6;</code>
     */
    public Builder mergeServerLocality(org.tensorflow.framework.DeviceLocality value) {
      if (serverLocalityBuilder_ == null) {
        if (serverLocality_ != null) {
          serverLocality_ =
            org.tensorflow.framework.DeviceLocality.newBuilder(serverLocality_).mergeFrom(value).buildPartial();
        } else {
          serverLocality_ = value;
        }
        onChanged();
      } else {
        serverLocalityBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional information on server-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality server_locality = 6;</code>
     */
    public Builder clearServerLocality() {
      if (serverLocalityBuilder_ == null) {
        serverLocality_ = null;
        onChanged();
      } else {
        serverLocality_ = null;
        serverLocalityBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Optional information on server-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality server_locality = 6;</code>
     */
    public org.tensorflow.framework.DeviceLocality.Builder getServerLocalityBuilder() {
      
      onChanged();
      return getServerLocalityFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional information on server-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality server_locality = 6;</code>
     */
    public org.tensorflow.framework.DeviceLocalityOrBuilder getServerLocalityOrBuilder() {
      if (serverLocalityBuilder_ != null) {
        return serverLocalityBuilder_.getMessageOrBuilder();
      } else {
        return serverLocality_ == null ?
            org.tensorflow.framework.DeviceLocality.getDefaultInstance() : serverLocality_;
      }
    }
    /**
     * <pre>
     * Optional information on server-side device locality.
     * </pre>
     *
     * <code>.tensorflow.DeviceLocality server_locality = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tensorflow.framework.DeviceLocality, org.tensorflow.framework.DeviceLocality.Builder, org.tensorflow.framework.DeviceLocalityOrBuilder> 
        getServerLocalityFieldBuilder() {
      if (serverLocalityBuilder_ == null) {
        serverLocalityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.tensorflow.framework.DeviceLocality, org.tensorflow.framework.DeviceLocality.Builder, org.tensorflow.framework.DeviceLocalityOrBuilder>(
                getServerLocality(),
                getParentForChildren(),
                isClean());
        serverLocality_ = null;
      }
      return serverLocalityBuilder_;
    }

    private com.google.protobuf.Any transportOptions_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> transportOptionsBuilder_;
    /**
     * <pre>
     * Optional, implementation-specific data.
     * </pre>
     *
     * <code>.google.protobuf.Any transport_options = 7;</code>
     * @return Whether the transportOptions field is set.
     */
    public boolean hasTransportOptions() {
      return transportOptionsBuilder_ != null || transportOptions_ != null;
    }
    /**
     * <pre>
     * Optional, implementation-specific data.
     * </pre>
     *
     * <code>.google.protobuf.Any transport_options = 7;</code>
     * @return The transportOptions.
     */
    public com.google.protobuf.Any getTransportOptions() {
      if (transportOptionsBuilder_ == null) {
        return transportOptions_ == null ? com.google.protobuf.Any.getDefaultInstance() : transportOptions_;
      } else {
        return transportOptionsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional, implementation-specific data.
     * </pre>
     *
     * <code>.google.protobuf.Any transport_options = 7;</code>
     */
    public Builder setTransportOptions(com.google.protobuf.Any value) {
      if (transportOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        transportOptions_ = value;
        onChanged();
      } else {
        transportOptionsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional, implementation-specific data.
     * </pre>
     *
     * <code>.google.protobuf.Any transport_options = 7;</code>
     */
    public Builder setTransportOptions(
        com.google.protobuf.Any.Builder builderForValue) {
      if (transportOptionsBuilder_ == null) {
        transportOptions_ = builderForValue.build();
        onChanged();
      } else {
        transportOptionsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Optional, implementation-specific data.
     * </pre>
     *
     * <code>.google.protobuf.Any transport_options = 7;</code>
     */
    public Builder mergeTransportOptions(com.google.protobuf.Any value) {
      if (transportOptionsBuilder_ == null) {
        if (transportOptions_ != null) {
          transportOptions_ =
            com.google.protobuf.Any.newBuilder(transportOptions_).mergeFrom(value).buildPartial();
        } else {
          transportOptions_ = value;
        }
        onChanged();
      } else {
        transportOptionsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional, implementation-specific data.
     * </pre>
     *
     * <code>.google.protobuf.Any transport_options = 7;</code>
     */
    public Builder clearTransportOptions() {
      if (transportOptionsBuilder_ == null) {
        transportOptions_ = null;
        onChanged();
      } else {
        transportOptions_ = null;
        transportOptionsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Optional, implementation-specific data.
     * </pre>
     *
     * <code>.google.protobuf.Any transport_options = 7;</code>
     */
    public com.google.protobuf.Any.Builder getTransportOptionsBuilder() {
      
      onChanged();
      return getTransportOptionsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional, implementation-specific data.
     * </pre>
     *
     * <code>.google.protobuf.Any transport_options = 7;</code>
     */
    public com.google.protobuf.AnyOrBuilder getTransportOptionsOrBuilder() {
      if (transportOptionsBuilder_ != null) {
        return transportOptionsBuilder_.getMessageOrBuilder();
      } else {
        return transportOptions_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : transportOptions_;
      }
    }
    /**
     * <pre>
     * Optional, implementation-specific data.
     * </pre>
     *
     * <code>.google.protobuf.Any transport_options = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getTransportOptionsFieldBuilder() {
      if (transportOptionsBuilder_ == null) {
        transportOptionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getTransportOptions(),
                getParentForChildren(),
                isClean());
        transportOptions_ = null;
      }
      return transportOptionsBuilder_;
    }

    private java.lang.Object srcDevice_ = "";
    /**
     * <pre>
     * For annotating timeline and device incarnation check.
     * </pre>
     *
     * <code>string src_device = 8;</code>
     * @return The srcDevice.
     */
    public java.lang.String getSrcDevice() {
      java.lang.Object ref = srcDevice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srcDevice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * For annotating timeline and device incarnation check.
     * </pre>
     *
     * <code>string src_device = 8;</code>
     * @return The bytes for srcDevice.
     */
    public com.google.protobuf.ByteString
        getSrcDeviceBytes() {
      java.lang.Object ref = srcDevice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcDevice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * For annotating timeline and device incarnation check.
     * </pre>
     *
     * <code>string src_device = 8;</code>
     * @param value The srcDevice to set.
     * @return This builder for chaining.
     */
    public Builder setSrcDevice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      srcDevice_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For annotating timeline and device incarnation check.
     * </pre>
     *
     * <code>string src_device = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSrcDevice() {
      
      srcDevice_ = getDefaultInstance().getSrcDevice();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For annotating timeline and device incarnation check.
     * </pre>
     *
     * <code>string src_device = 8;</code>
     * @param value The bytes for srcDevice to set.
     * @return This builder for chaining.
     */
    public Builder setSrcDeviceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      srcDevice_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dstDevice_ = "";
    /**
     * <pre>
     * Optional, for annotating the timeline.
     * </pre>
     *
     * <code>string dst_device = 9;</code>
     * @return The dstDevice.
     */
    public java.lang.String getDstDevice() {
      java.lang.Object ref = dstDevice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dstDevice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional, for annotating the timeline.
     * </pre>
     *
     * <code>string dst_device = 9;</code>
     * @return The bytes for dstDevice.
     */
    public com.google.protobuf.ByteString
        getDstDeviceBytes() {
      java.lang.Object ref = dstDevice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dstDevice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional, for annotating the timeline.
     * </pre>
     *
     * <code>string dst_device = 9;</code>
     * @param value The dstDevice to set.
     * @return This builder for chaining.
     */
    public Builder setDstDevice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dstDevice_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional, for annotating the timeline.
     * </pre>
     *
     * <code>string dst_device = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDstDevice() {
      
      dstDevice_ = getDefaultInstance().getDstDevice();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional, for annotating the timeline.
     * </pre>
     *
     * <code>string dst_device = 9;</code>
     * @param value The bytes for dstDevice to set.
     * @return This builder for chaining.
     */
    public Builder setDstDeviceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dstDevice_ = value;
      onChanged();
      return this;
    }

    private long requestId_ ;
    /**
     * <pre>
     * Depending on the RPC system in use, it may be necessary to set this
     * id to detect resends of RPCs where the server is not aware that
     * the prior RPC failed.
     * </pre>
     *
     * <code>int64 request_id = 10;</code>
     * @return The requestId.
     */
    public long getRequestId() {
      return requestId_;
    }
    /**
     * <pre>
     * Depending on the RPC system in use, it may be necessary to set this
     * id to detect resends of RPCs where the server is not aware that
     * the prior RPC failed.
     * </pre>
     *
     * <code>int64 request_id = 10;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(long value) {
      
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Depending on the RPC system in use, it may be necessary to set this
     * id to detect resends of RPCs where the server is not aware that
     * the prior RPC failed.
     * </pre>
     *
     * <code>int64 request_id = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      
      requestId_ = 0L;
      onChanged();
      return this;
    }

    private long srcIncarnation_ ;
    /**
     * <pre>
     * Incarnation number of the source device, used to detect worker failures.
     * </pre>
     *
     * <code>uint64 src_incarnation = 11;</code>
     * @return The srcIncarnation.
     */
    public long getSrcIncarnation() {
      return srcIncarnation_;
    }
    /**
     * <pre>
     * Incarnation number of the source device, used to detect worker failures.
     * </pre>
     *
     * <code>uint64 src_incarnation = 11;</code>
     * @param value The srcIncarnation to set.
     * @return This builder for chaining.
     */
    public Builder setSrcIncarnation(long value) {
      
      srcIncarnation_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Incarnation number of the source device, used to detect worker failures.
     * </pre>
     *
     * <code>uint64 src_incarnation = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSrcIncarnation() {
      
      srcIncarnation_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.RecvBufRequest)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.RecvBufRequest)
  private static final org.tensorflow.distruntime.RecvBufRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.distruntime.RecvBufRequest();
  }

  public static org.tensorflow.distruntime.RecvBufRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecvBufRequest>
      PARSER = new com.google.protobuf.AbstractParser<RecvBufRequest>() {
    @java.lang.Override
    public RecvBufRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RecvBufRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RecvBufRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecvBufRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.tensorflow.distruntime.RecvBufRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

