// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker.proto

package org.tensorflow.distruntime;

public interface RunGraphResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.RunGraphResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  java.util.List<org.tensorflow.framework.NamedTensorProto> 
      getRecvList();
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  org.tensorflow.framework.NamedTensorProto getRecv(int index);
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  int getRecvCount();
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  java.util.List<? extends org.tensorflow.framework.NamedTensorProtoOrBuilder> 
      getRecvOrBuilderList();
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto recv = 1;</code>
   */
  org.tensorflow.framework.NamedTensorProtoOrBuilder getRecvOrBuilder(
      int index);

  /**
   * <pre>
   * If the request asked for execution stats, the cost graph, or the partition
   * graphs, these are returned here.
   * TODO(suharshs): Package these in a RunMetadata instead.
   * </pre>
   *
   * <code>.tensorflow.StepStats step_stats = 2;</code>
   * @return Whether the stepStats field is set.
   */
  boolean hasStepStats();
  /**
   * <pre>
   * If the request asked for execution stats, the cost graph, or the partition
   * graphs, these are returned here.
   * TODO(suharshs): Package these in a RunMetadata instead.
   * </pre>
   *
   * <code>.tensorflow.StepStats step_stats = 2;</code>
   * @return The stepStats.
   */
  org.tensorflow.framework.StepStats getStepStats();
  /**
   * <pre>
   * If the request asked for execution stats, the cost graph, or the partition
   * graphs, these are returned here.
   * TODO(suharshs): Package these in a RunMetadata instead.
   * </pre>
   *
   * <code>.tensorflow.StepStats step_stats = 2;</code>
   */
  org.tensorflow.framework.StepStatsOrBuilder getStepStatsOrBuilder();

  /**
   * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
   * @return Whether the costGraph field is set.
   */
  boolean hasCostGraph();
  /**
   * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
   * @return The costGraph.
   */
  org.tensorflow.framework.CostGraphDef getCostGraph();
  /**
   * <code>.tensorflow.CostGraphDef cost_graph = 3;</code>
   */
  org.tensorflow.framework.CostGraphDefOrBuilder getCostGraphOrBuilder();

  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  java.util.List<org.tensorflow.framework.GraphDef> 
      getPartitionGraphList();
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  org.tensorflow.framework.GraphDef getPartitionGraph(int index);
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  int getPartitionGraphCount();
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  java.util.List<? extends org.tensorflow.framework.GraphDefOrBuilder> 
      getPartitionGraphOrBuilderList();
  /**
   * <code>repeated .tensorflow.GraphDef partition_graph = 4;</code>
   */
  org.tensorflow.framework.GraphDefOrBuilder getPartitionGraphOrBuilder(
      int index);

  /**
   * <pre>
   * If store_errors_in_response_body is true in the request, then
   * optionally the server may return an OK status for the RPC and
   * fill the true status into the fields below, to allow for messages
   * that are too long to fit in metadata.
   * </pre>
   *
   * <code>.tensorflow.error.Code status_code = 5;</code>
   * @return The enum numeric value on the wire for statusCode.
   */
  int getStatusCodeValue();
  /**
   * <pre>
   * If store_errors_in_response_body is true in the request, then
   * optionally the server may return an OK status for the RPC and
   * fill the true status into the fields below, to allow for messages
   * that are too long to fit in metadata.
   * </pre>
   *
   * <code>.tensorflow.error.Code status_code = 5;</code>
   * @return The statusCode.
   */
  org.tensorflow.framework.Code getStatusCode();

  /**
   * <code>string status_error_message = 6;</code>
   * @return The statusErrorMessage.
   */
  java.lang.String getStatusErrorMessage();
  /**
   * <code>string status_error_message = 6;</code>
   * @return The bytes for statusErrorMessage.
   */
  com.google.protobuf.ByteString
      getStatusErrorMessageBytes();
}
